
author = "Anne den Hartog"
title = "Thermally comfortable urban mobility: operationalizing urban microclimate data into a pedestrian routing tool"
graduation-year = 2026
graduation-month = "June"
supervisor1 = "Clara Garcia-Sanchez"
supervisor2 = "Daniela Maiullari"
supervisor3 = "Lukas Beuster"
coreader = "Akshay Patil"
graduation-group = "3D geoinformation group"

