#import "../template.typ": *
/*
- *RQ:* 
  - *RQ1:* 
  - *RQ2:* H
  - *RQ3:* What does scalability mean for a pedestrian routing tool particularly regarding its potential for spatial and functional extension?
  - *RQ4:* 
  */
= Discussion and conclusion
#todo(position: "inline")[make sure RQ's match with introduction]
This chapter will first discuss the results, with the 
== Discussion of results
In this section the results of the thesis are discussed and evaluated. 
- Any insights into scalability and performance cannot be removed from implementation. Since the way things are implemented, decides what the performance will be. 

- THis thesis aimed to provide insights into how technical vooruitgang can open up opportunities -- like solweig-gpu, and cloud optimized formats. 

- Not just a scalable route-planner but also an more general insight into the possibilities of solving performance issues with smart data structures and technologies. Not necessitating entire methodological shifts. 

- Robustness and abstraction. Usually UMC modelling results are viewed and analysed by experts on the subject matter. It's an end product that can be used for analysis. In this application it's the base on which further abstractions are performed. This makes the process vulnerable to mistakes. Since the analysis is only done while the tool is being developed it becomes more difficult to abstract things away.

- Sometimes the algorithm introduces a route that has a higher utci_median than the shortest route. This is because the algorithm harshly punishes very hot edges. However, in these cases it can happen that the adjusted route will avoid this extremely hot edge, but crossing a more medium hot edges, causing the average 
- Results in absolute terms are not as good as in other research in terms of reduced heat stress. In part can be attributed to the climate in the Netherlands. Since most other research was done in hot climates. Additionally, @rusig_reducing_2017 achieved a higher lowering of temperature but their routes were on average 2km long, thus it is to be expected that 

== Research questions
=== Main RQ
#quote[*RQ: * _How can urban microclimate data generated by UMEP's SOLWEIG be transformed and integrated into a fully open-source, scalable pedestrian routing tool to support thermally comfortable mobility decisions at the individual level?_]

The entire pipeline to go from input data to routeplanner consists of multiple separate components. All of which have different tasks and bottlenecks. The right datastructure is thus dependent on the component and hsould be custom. To support this need for different datastructures depending on the componenet a the code needs to be designed in a modular way. With high coshesion wihtin teh component, code that shares a conceptual function stays together. And low coupling, a change in one component does not affect the other componenets -> itroduce no limitations becasue of design descisions in a different componenet. 

=== Operationalizing UMEP outputs
#quote[*RQ1: * _What design strategies and data structures enable the effective use of UMEP outputs in a scalable pedestrian route planning application?_] 

The first design strategy is to make the preparation of input data as automatic and reusable as possible. Because UMEP/SOLWEIG simulations require several spatial and meteorological inputs, the workflow should avoid manual, case-specific preparation steps where possible. This improves reproducibility and makes it easier to apply the same pipeline to other study areas. However, the actual performance of running SOLWEIG remains dependent on the available hardware and the size and resolution of the input data. Therefore, the workflow can be designed to support scalability, but exact computation times cannot be generalized without testing them in a specific computing environment.

A second important strategy is to transform the SOLWEIG outputs into a data structure that matches the needs of the routing application. Instead of using the full raster outputs directly during route calculation, the environmental information is sampled in advance and attached to the pedestrian network. In this way, the pedestrian network becomes the main data structure for routing as well as for storing relevant environmental attributes. This structure is also functionally extendable, because additional variables can be appended to the network edges and described in the metadata without changing the overall system design.

Lastly, to support this transformation, a fitting choice for the file format is important. In this thesis, the SOLWEIG outputs were merged into a Zarr file, which supports efficient handling of large spatio-temporal raster data. These files can then be sampled and reduced to edge-based attributes efficiently.

=== Routing algorithm
#quote[*RQ2: * _How can established weighted-cost routing algorithms incorporate SOLWEIG outputs and be implemented and adapted to automatically generate thermally conscious pedestrian routes?_]

The thermal attributes derived from SOLWEIG, in this case median UTCI, are attached directly to the pedestrian network and used by the cost function of the routing algorithm. Edges with less favourable thermal conditions receive a higher cost, allowing the algorithm to generate thermally conscious routes. The algorithm design is informed by established weighted-cost routing approaches used in research on environmentally conscious routing, where route choice is influenced not only by distance but also by additional environmental cost components.

First, the algorithm needed to be dynamic, because the cost of the next edge can depend not only on its environmental attributes, but also on the current state of the route and the edges that have already been taken. Therefore, the shortest path algorithm needs to be state-aware. Second, the routing should not depend only on researcher-defined weights. By allowing users to adjust the importance of environmental attributes, the tool can better account for different preferences and changing circumstances. This also supports functional scalability, because new environmental attributes can be added to the network and incorporated into the weighting structure without changing the overall routing approach.

=== Data completeness and abstraction
#quote[*RQ3: * _How do assumptions in data quality (completeness) in the digital representation of the pedestrian network influence the applicability of the resulting tool?_]

- say something about the importance of abstraction/data loss, maybe not entirely suited to being a research question and more a well informed thing for future work.
=== Scalability 
#quote[*RQ3: * _What does scalability mean for a pedestrian routing tool particularly regarding its potential for spatial and functional extension?_]

In the context of this thesis, scalability refers to the extent to which the pedestrian routing tool can be extended beyond its initial implementation without requiring fundamental redesign. This concerns both spatial scalability, meaning the ability to apply the tool to larger or different geographic areas, and functional scalability, meaning the ability to incorporate new routing criteria as understanding of comfortable pedestrian routing develops. Scalability is therefore not understood only as computational performance, but also as the capacity of the tool’s structure to support future adaptation.

Spatial scalability is primarily incorporated through performance-aware and reusable processing. The tool can be extended to additional geographic areas by applying the same sequence of data preparation, network annotation, and routing steps to a new spatial extent. However, as the study area increases, the number of raster cells, network edges, and possible route calculations also increases. Performance therefore becomes central to scalability, because spatial extension is only practical if the required preprocessing and routing computations remain manageable. #todo[end with something about this thesis?, Running routes should also be quick etc.]

Reusability is another condition for scalability. The tool combines multiple data sources, software components, and methodological assumptions. Because environmental data availability and preprocessing requirements may differ between regions, especially across national borders, the individual components should not be too tightly dependent on one specific dataset or implementation choice. By organising the tool into coherent components with limited coupling, parts of the workflow can be reused where possible, while individual components can be replaced or adapted when different input data or methods are required. This supports scalability because changes in one part of the pipeline do not necessarily require changes to the entire tool.

Functional scalability is incorporated by treating the routing criteria as extendable rather than fixed. In this implementation, thermal comfort derived from UTCI categories is used to inform route choice, but this is only one possible interpretation of comfortable pedestrian routing. Other variables, such as visual interest, could also be relevant to pedestrian comfort and route preference @manley_cognitive_2021. To be scalable the tool therefore needs data structures and routing logic that allow additional edge attributes or weighting strategies to be introduced without redesigning the complete routing system.

Finally, scalability also depends on the ease with which extension can be carried out. Ideally, scaling the tool to a new area or adding new functionality would be limited mainly by computational resources. In practice, this was only partly achieved. Since the transfer between components still requires some manual work, meaning that scaling is not yet fully automatic. The tool therefore demonstrates a scalable structure, but its practical scalability could be improved by further automating the connections between preprocessing, network annotation, routing, and front-end use. 

#todo[Maybe a part of this is results--generalizable insights?]

== Contributions
- A web-ui showcasing the tool 
- A pedestrian routing tool that was built on a scalable/extensible structure.
- Insights into the importance of implementation choices with regard to the performance and scalability of these tools.

== Limitations
- weather/climate: 
  - no extra weather types considered. So there is no distinction between seasons or days.
- computation time of input data (data preparation)
  - cloud based formats 
- UTCI but not person specific like PET
  - include UMEP's URock to generate detailed 2d wind maps
- pedestrian network from OSM 
  - Dependence on user annotated road tags introduces uncertainty
  - Almost all roads (unless sidewalk geometry is explicitly mapped) are mapped as center lines, while pedestrians almost always make use of sidewalks. So the sampling of the UTCI data is not done on the spot the pedestrian is actually walking. It's just an approximation.
- SOLWEIG\_GPU implementation is not capable of considering negative height values (values below sea level)
- Loss of an expert's view:
  - Since the 'interpretation' of the UTCI map is done automatically there is no human expert to look and interpret the results. This means that at scale mistakes and issues might fall through the cracks. This can be both mistakes from the model or the implementation.


== Future work
- UTCI was used but this is not person specific, a value like PET would be more appropriate. However this needs wind information that is not generated in this thesis.The algorithm could be extended to calculate weights based on PET score by using the TMRT edge values if wind is also available. (I can do a basic implementation)

- Apply this methodology to different climates, to see if the methodology can achieve positive results that are similar to previous work. This would also test the scalability of the method & could be an easy open source way to improve the adaptive capacity of communities that are disproportionally effected by climate change.

- Cloud native formats can greatly reduce the need for downloading and merging entire files, since they allow for fast data retrieval. Once these formats become broadly available the performance bottlenecks in the data preparation might not be a bottleneck any more.

- Extend the pedestrian network with indoor paths.

- no weather information: think of using user preferences effectively to limit the amount off 