#import "../template.typ": *

= Discussion and conclusion
<chap:discussion-conclusion>
This chapter will first quickly summarise the main points in the results chapter. Then the specific contributions, limitations and recommendations for future work are given. Finally it concludes by answering the research questions posed at the beginning of this thesis.

== Contributions
- A fully open-source methodology for generating thermally conscious pedestrian routes, implemented in a locally deployable web-based tool for route interaction and visualisation.

- Insights into how implementation-level design choices affect the performance, scalability, and interpretability of urban microclimate-informed pedestrian routing tools.

== Limitations
*Climatic and geographic transferability: * The results are based on a Rotterdam case-study area under one high-heat weather scenario. The weighting scheme and routing outcomes may therefore not transfer directly to cities with warmer, drier, or more extreme climates, or to other seasonal and meteorological conditions. Thus, the transferability of the proposed approach to other climatic contexts should be evaluated carefully before broader application.

*Thermal-comfort indicator: * The routing tool uses UTCI as a generalized indicator of thermal stress. UTCI is based on a predefined reference person and does not account for individual differences such as age or sex. As a result, the route planner cannot directly represent the thermal vulnerability of specific pedestrian groups. The main form of user customisation is limited to adjusting the user-defined weights.

*Thermal-comfort validation: * The validation shows that the tool can reduce modelled UTCI exposure compared with the shortest route, but it does not validate whether pedestrians would actually experience these routes as being more comfortable. No field measurements, human-subject testing, or perception-based validation were conducted. 

*SOLWEIG\_GPU: * The SOLWEIG\_GPU implementation used in this thesis could not process negative height values, such as elevation values below sea level. Therefore, negative values in the DTM and DSM were set to zero before simulation. This preprocessing step may have introduced inaccuracies in the representation of the urban surface. Consequently, local variations in terrain and building height may not have been fully preserved in the thermal-comfort simulations.

*Performance and scalability evaluation: * The runtime results should be interpreted as indicative rather than as a general benchmark. They were measured on specific hardware and for a limited number of spatial cases. The thesis therefore demonstrates a scalable software structure, but not full large-scale operational scalability. 

*Pedestrian network representation: * The pedestrian network used in this thesis is based on OpenStreetMap data and therefore inherits both the advantages and limitations of a crowd-sourced dataset. Tagging practices may vary between contributors, meaning that similar pedestrian features can be represented inconsistently or remain unmapped. In addition, many road segments are represented as centre lines, while pedestrians for example often move along sidewalks. This may have introduced inaccuracies when sampling the UTCI raster, because the network geometry does not always correspond with the actual locations of pedestrian movement. The generated routes should therefore be interpreted as thermally conscious routes within the available digital network representation, rather than as exact representations of pedestrian-level exposure in the real world.

*Automated abstraction of microclimate outputs: * Urban microclimate modelling outputs are typically inspected and interpreted by domain experts as an end product for analysis, whereas in this thesis they form the basis for additional automated abstractions. This makes the workflow more vulnerable to modelling errors, preprocessing issues, or local anomalies that may remain unnoticed once the data are converted into routing weights. The risk is especially relevant for applications at scale, where results may be generated for larger areas or different contexts without detailed expert inspection of each intermediate output.


== Future work
*Scalability: * The workflow can be applied to larger and more diverse study areas in order to evaluate its practical scalability. In this thesis, scalability was investigated mainly at the level of software structure, data formats, and component design. A next step would be to test whether the same workflow can be applied across different neighbourhoods, cities, climatic contexts, and weather scenarios without requiring substantial methodological redesign. This would make it possible to evaluate both the spatial transferability of the tool and the sensitivity of the routing outcomes to different thermal conditions.

*Thermal comfort validation:* The generated routes should be validated against actual pedestrian experience. This could be addressed for example through field measurements or feedback collected through the web-based interface. Such validation would be especially important for refining the weighting scheme, since the current routing costs are only based on modelled exposure rather than observed user preferences.


*Person-specific and multi-variable routing: * The current implementation uses UTCI as a generalized thermal-stress indicator and allows users to adjust the importance of thermal comfort through weighting. However, it does not directly model differences between pedestrian groups or individual vulnerability. Future work could investigate the use of alternative thermal-comfort indicators, such as PET, if the required meteorological inputs are available. In addition, the routing framework could be extended with other environmental or experiential variables, such as greenery, shade, air quality, noise, or visual comfort. This would also allow further investigation of automatic or data-driven weighting schemes, rather than relying only on predefined or user-defined weights.

*Performance: * The most substantial performance bottlenecks occurred during data preparation and SOLWEIG execution. Future work could therefore explore cloud-native geospatial data access, which may reduce the need to merge complete source tiles when generating the input data before running the model. Alternative approaches to generating thermal-comfort maps, including machine-learning-based approximations @ma_street_2025, could also be investigated, particularly if they reduce computation time while preserving sufficient spatial accuracy for routing applications. Once the effect of spatial resolution on routing accuracy has been validated, lower-resolution simulations could also be explored as a performance optimisation strategy.

*Pedestrian network: * Future research could compare centre-line-based networks with sidewalk-aware networks, manually corrected pedestrian geometries, or datasets that include indoor and semi-indoor pedestrian paths. This would make it possible to quantify how network representation affects sampled UTCI values, route selection, and the estimated thermal benefit of the generated routes.

== Research overview
=== Main RQ
#quote[*RQ: * _How can urban microclimate data generated by UMEP's SOLWEIG be transformed and integrated into a fully open-source, scalable pedestrian routing tool to support thermally conscious mobility decisions at the individual level?_]

The pipeline from input data to route planner consists of several separate components, each with its own function, data requirements, and performance bottlenecks. As a result, there is no single data structure that is optimal for the entire workflow. Instead, the representation of the data should be adapted to the task of each component. This requires a modular software design in which related functionality is grouped within cohesive components, while dependencies between components remain limited. The open-source design is central to this workflow, because it allows the transformation from SOLWEIG-based microclimate modelling to route generation to remain reproducible, inspectable, and adaptable beyond the case-study implementation.

This modular design is reflected in the way spatial information changes form throughout the workflow. SOLWEIG outputs represent thermal conditions as gridded raster surfaces, which are appropriate for microclimate modelling but not directly usable by a graph-based routing algorithm. During network annotation, these raster values are sampled and aggregated into edge-level attributes. These attributes then become part of the routing cost, allowing thermal conditions to be incorporated into path calculation without requiring the routing algorithm to access the full raster output directly.

In this way, the tool supports thermally conscious mobility decisions by translating urban microclimate information into a route alternative for an individual trip. Rather than only providing a map of thermal conditions, the workflow makes this information actionable by using modelled heat exposure directly in route generation. The resulting route reflects a trade-off between distance and thermal comfort based on the selected routing settings, allowing the user to choose a route that is informed by local thermal conditions.

=== Operationalizing UMEP outputs
#quote[*RQ1: * _What design strategies and data structures enable the effective use of UMEP outputs in a scalable pedestrian route planning application?_] 

The first design strategy is to make the preparation of input data as automatic and reusable as possible. Because UMEP/SOLWEIG simulations require several spatial and meteorological inputs, the workflow should avoid manual, case-specific preparation steps where possible. This improves reproducibility and makes it easier to apply the same pipeline to other study areas. However, the actual performance of running SOLWEIG remains dependent on the available hardware and the size and resolution of the input data. Therefore, the workflow can be designed to support scalability, but exact computation times cannot be generalized without testing them in a specific computing environment.

A second important strategy is to transform the SOLWEIG outputs into a data structure that matches the needs of the routing application. Instead of using the full raster outputs directly during route calculation, the environmental information is sampled in advance and attached to the pedestrian network. In this way, the pedestrian network becomes the main data structure for routing as well as for storing relevant environmental attributes. This structure is also functionally extendable, because additional variables can be appended to the network edges and described in the metadata without changing the overall system design.

Lastly, to support this transformation, appropriate file formats for the use-case should be chosen. In this thesis, the SOLWEIG outputs were merged into a Zarr file, which supports efficient handling of large spatio-temporal raster data. These files can then be sampled and reduced to edge-based attributes efficiently.

=== Routing algorithm
#quote[*RQ2: * _How can established weighted-cost routing algorithms incorporate SOLWEIG outputs and be implemented and adapted to automatically generate thermally conscious pedestrian routes?_]

The thermal attributes derived from SOLWEIG are attached directly to the pedestrian network and used by the cost function of the routing algorithm. Edges with less favourable thermal conditions receive a higher cost, allowing the algorithm to generate thermally conscious routes. For the algorithm to be applicable in a thermally conscious routing context, it needed to incorporate both dynamic thermal exposure and adjustable user preferences.

First, the algorithm needed to be dynamic, because the cost of the next edge can depend not only on its environmental attributes, but also on the current state of the route and the edges that have already been taken. Therefore, the shortest path algorithm needs to be state-aware. Second, the routing should not depend only on researcher-defined weights. By allowing users to adjust the importance of environmental attributes, the tool can better account for different preferences and changing circumstances. 

=== Scalability 
#quote[*RQ3: * _What does scalability mean for a pedestrian routing tool particularly regarding its potential for spatial and functional extension?_]
In the context of this thesis, scalability refers to the ability of the pedestrian routing tool to be extended beyond its initial case-study implementation without requiring fundamental redesign. This includes spatial scalability, meaning application to larger or different geographic areas, and functional scalability, meaning the ability to incorporate additional routing criteria as the definition of thermally comfortable pedestrian routing develops. Scalability is therefore not limited to computation time, but also concerns whether the tool’s structure can support future adaptation.

For this type of workflow, scalability depends on three related implementation principles: performance, modularity, and reusability. Performance is necessary because spatial extension increases the number of raster cells, network edges, and route calculations. If preprocessing, network annotation, or routing become too slow, the tool cannot be practically extended. Modularity is necessary because the workflow combines distinct tasks, including data preparation, microclimate simulation, network annotation, and routing, which each have different data requirements and bottlenecks. Reusability is necessary because future applications may use different input data, environmental variables, or interfaces.

// In the context of this thesis, scalability refers to the extent to which the pedestrian routing tool can be extended beyond its initial implementation without requiring fundamental redesign. This concerns both spatial scalability, meaning the ability to apply the tool to larger or different geographic areas, and functional scalability, meaning the ability to incorporate new routing criteria as understanding of comfortable pedestrian routing develops. Scalability is therefore not understood only as computational performance, but also as the capacity of the tool’s structure to support future adaptation.

// Spatial scalability is primarily incorporated through performance-aware and reusable processing. The tool can be extended to additional geographic areas by applying the same sequence of data preparation, network annotation, and routing steps to a new spatial extent. However, as the study area increases, the number of raster cells, network edges, and possible route calculations also increases. Performance therefore becomes central to scalability, because spatial extension is only practical if the required preprocessing and routing computations remain manageable. #todo[end with something about this thesis?, Running routes should also be quick etc.]

// Reusability is another condition for scalability. The tool combines multiple data sources, software components, and methodological assumptions. Because environmental data availability and preprocessing requirements may differ between regions, especially across national borders, the individual components should not be too tightly dependent on one specific dataset or implementation choice. By organising the tool into coherent components with limited coupling, parts of the workflow can be reused where possible, while individual components can be replaced or adapted when different input data or methods are required. This supports scalability because changes in one part of the pipeline do not necessarily require changes to the entire tool.

// Functional scalability is incorporated by treating the routing criteria as extendable rather than fixed. In this implementation, thermal comfort derived from UTCI categories is used to inform route choice, but this is only one possible interpretation of comfortable pedestrian routing. Other variables, such as visual interest, could also be relevant to pedestrian comfort and route preference @manley_cognitive_2021. To be scalable the tool therefore needs data structures and routing logic that allow additional edge attributes or weighting strategies to be introduced without redesigning the complete routing system.

// Finally, scalability also depends on the ease with which extension can be carried out. Ideally, scaling the tool to a new area or adding new functionality would be limited mainly by computational resources. In practice, this was only partly achieved. Since the transfer between components still requires some manual work, meaning that scaling is not yet automatic. The tool therefore demonstrates a scalable structure, but its practical scalability could be improved by further automating the connections between preprocessing, network annotation, routing, and front-end use. 


== Concluding thoughts

The broader implication of this thesis is that scalability in urban microclimate-informed routing cannot be separated from implementation. Data structures, file formats, software architecture, and network representations shape not only computational performance, but also the interpretability of the resulting routes. Treating these choices as methodological decisions rather than neutral technical details makes it possible to identify performance bottlenecks and address them through targeted design choices, without necessarily changing the underlying research objective.