#import "../template.typ": *

= Introduction <chap:intro>

Climate change is increasing the frequency and intensity of extreme weather events, including heatwaves, which pose growing risks to human health. Urban areas are especially vulnerable to the effects of heat due to phenomena like the urban heat island effect or the materials used @ipcc2022_technical. As highlighted by the IPCC (2022), the high concentration of people in cities means that climate impacts affect large populations simultaneously, but also that interventions in urban areas can deliver substantial benefits for the same reason. Improving the adaptive capacity of urban communities can therefore play a key role in managing the effects of climate change. @ipcc2022_policy

In everyday urban life, heat-related climate impacts can directly affect thermal comfort during outdoor activities, such as walking. With thermal comfort being defined as _"environmental conditions where an individual feels no thermal stress and exhibits no sign of thermal strain. In these circumstances, the net heat gain/loss of the body will be close to zero."_ @Oke_Mills_Christen_Voogt_2017_glossary. This state occurs from the interaction between the human body and its surrounding environment. So when the environment changes in temperature, the body experiences thermal stress. In outdoor settings, this concept is commonly referred to as Outdoor Thermal Comfort (OTC).

Poor outdoor thermal comfort can discourage walking and increase heat-related health issues, especially among vulnerable populations like older people, children, and individuals with pre-existing health conditions @foshag_how_2024. This is why OTC is not only related to environmental quality but also to public health and social equity. Outdoor thermal comfort is influenced by a wide range of parameters which can be grouped in two categories: environment-based (e.g., weather and climate conditions) and human-based (e.g., physiological characteristics) @aghamolaei_comprehensive_2023 (@background-info). 

While human-based factors determine how individuals respond to thermal conditions, environment-based factors shape these thermal conditions outdoors. In cities, this can vary substantially over short distances and time scales due to building geometry, surface materials, vegetation, and wind patterns. For example, even in a single street, the thermal conditions can differ wildly between a shaded area and a non-shaded area or between times of day. This spatial and temporal variability makes OTC particularly challenging to assess using measurements alone, and highlights the opportunity for urban microclimate modelling approaches to analyze OTC across space and time @Oke_Mills_Christen_Voogt_2017.

Urban microclimate modelling (UMC) uses various inputs to model environmental conditions in a small spatial and temporal resolution. A model that has solvers relevant for OTC is the open-source Urban Multi-scale Environmental Predictor (UMEP) developed by Lindberg et. al (2017). In this thesis, the SOLWEIG solver @lindberg_urban_2017 is used to estimate the mean radiant temperature. The URock solver @bernard_urock_2023 is used to simulate pedestrian-level wind conditions. This gives spatially explicit information on thermal stress, that in combination with human-based factors, can help inform OTC for pedestrians.

Tools like UMEP have primarily been used for research and long-term urban planning/design rather every day decision making for individuals. To support this everyday decision-making, this thesis focuses on integrating environmental data generated by UMEP into an open-source pedestrian routing tool. With the ultimate goal of improving the adaptive capacity of communities by supporting climate-aware mobility decisions.

Previous work on thermal comfort-oriented routing is characterized by differing methodologies, both in input data collection and routing algorithm design (@rout-env). These differences are partly caused by the data (or lack thereof) that was available for researchers to collect or use. Additionally, much of the existing research focuses primarily on demonstrating that comfortable routes can offer measurable benefits. Which provides important proof of concept insights. However, there has been less emphasis on the reproducibility, scalability, and openness of the underlying systems. As a result, most of the proposed approaches are either difficult to transfer across cities or have not been implemented in user-facing applications at all.

This thesis addresses these limitations by focusing on the development of a fully open-source tool for thermally comfortable pedestrian routing. First, the challenge of environmental data availability is addressed through the use of UMEP to model mean radiant temperature and wind. Secondly, this thesis will document and investigate the best practices on how to incorporate complex urban microclimate data in a scalable and accessible user-facing tool.

= Research questions and scope
<research-questions>
== Problem statement
Outdoor thermal comfort varies greatly across space and time. Models like UMEP can provide detailed estimates, but they are seldom used to help individual decision-making. Pedestrian routing provides a practical way to operationalize UMEP outputs by informing the generation of thermally comfortable paths. Existing research on thermally comfortable routing differs widely in input data and algorithmic design, with a focus "proof-of-concept" that caused a lack of attention to the reproducibility, scalability, and openness of the underlying systems. This thesis addresses these gaps by developing a framework for an open-source scalable user-facing routing tool. 

== Research question
All this leads to the following research question:
- *RQ:* How can urban microclimate data generated by UMEP's SOLWEIG be transformed and integrated into a fully open-source, scalable pedestrian routing tool to support thermally comfortable mobility decisions at the individual level?
  - *RQ1:* What design strategies and data structures enable the effective use of UMEP outputs in scalable web-based pedestrian routeplanning applications?
  - *RQ2:* How can established multi-objective routing algorithms incorporate UMEP outputs and be implemented and adapted to automatically generate thermally comfortable pedestrian routes?
  - *RQ3:* What does scalability mean for a pedestrian routing tool particularly regarding its potential for spatial and functional extension?
  - *RQ4:* How do assumptions in data quality (completeness) in the digital representation of the pedestrian network influence the applicability of the resulting tool? #todo[needs rewording]
  
== Scope
This thesis has a design-based approach, where the goal is to develop and evaluate a framework for incorporating UMEP outputs in a pedestrian routing tool. Not only focussing on the routing results, but also on produce generalizable design strategies for working with UMEP outputs in scalable, web-based applications. Due to the complexity of the data the spatial scope of this research will be limited to one city in the Netherlands: Rotterdam. With extensibility being included as a core design principle. Limiting the area for which this tool is developed makes it feasible to explore the design strategies in depth. 
The UMEP solvers that are used:
- SOLWEIG for Mean Radiant Temperature
- URock for wind
- PET by combining these two outputs.
The scope will be further limited by only focussing on high heat days, since the negative health
effects of heat stress are well documented. Also only pedestrians will be considered, since biking is
strongly constrained by available infrastructure.