#import "../template.typ": *

= Methodology
<chap:methodology>
#todo(position: "inline")[*This chap should answer: what did I do as a research process, what does the tool look like and how did I evaluate everything*]
This section first describes the research approach, which contextualizes the method used in this thesis using methodologies described in literature. Secondly, the study itself is described in large(r) steps. Then the data and tools which were used are described. Finally the separate software components of the final are described.
 
== Research approach (contextualize study method)
This thesis adopts a Design Science Research (DSR) methodology in which knowledge is generated through the iterative design, implementation, and evaluation of an artefact @runeson_design_2020 @wohlin_design_2021. Here that artefact is a open-source pedestrian routing tool that uses UMEP outputs to generate routes that avoid heat stress #todo[ensure consistency with rest of thesis]. The final tool serves both as a result of the research and as a way to investigate strategies for integrating urban microclimate data into web-based routing applications. To ensure that the design process yields generalizable insights, systematic evaluation is conducted throughout all stages of development @van_rensburg_model_2019.

@fig:methods shows how reflective DSR is applied in this thesis. 
#figure(
  image("../figs/methods/methods_diagram.png", width: 80%),
  caption: [
    Overview methodological approach
  ],
) <fig:methods> 

First literature is used to conceptualize the problem and identify the main design requirements. Then a solution is designed, which is validated according to the previously defined requirements. After which reflexive evaluation is used to readjust the problem conceptualization and requirements for the next design iteration. 

This process reflects the practical orientation of design science research for software engineering. Where the contribution of the research stems from its ability to solve a problem @runeson_design_2020. This idea is encompassed in the concept of utility, as described by Hevner et al.:_“If the artifact does not solve the problem (search, implementability), it has no utility. If utility is not demonstrated (evaluation), then there is no basis upon which to accept the claims that it provides any contribution”_ @hevner_utility_2004.

Utility is not only achieved through formal validation against predefined requirements, but also through insights generated by the iterative process with which the final tool is built. To place these insights into context we need to explicitly mention the role of the researcher/designer. The tool is designed through a "sequence of expert activities" @hevner_utility_2004, so even design iterations that were later upended can teach us something about how these systems are usually developed. In social sciences Finlay (2002) describes this position as "where researchers engage in explicit, self-aware analysis of their own role" and calls this reflexivity @finlay_outing_2002. In this thesis explicitly acknowledges that the expertise of the researcher shapes both the final tool but also the direction of inquiry. And draws generalized lessons not just from the final tool, but also the entire process of inquiry. Acknowledging that the fact that the researcher (who has expertise) decided on a course of action provides information on how assumptions and descriptions from previous research can shape the Initial implementation choice.

The iterative design process makes this research emergent; "Emergent design involves data collection and analysis procedures that can evolve over the course of a research project in response to what is learned in the earlier parts of the study"  @morgan_emergent_2008. This means that insights gained during the process can change and are expected to shape the direction of inquiry. 

== Describe the study (document the research process)
<research-steps>
Existing research has shown the possibility and usefulness of thermally informed routing @foshag_how_2024 @ma_active_2025 @rusig_reducing_2017 @wen_walking_smart_2025, but paid less attention to the technical foundations. This thesis addresses this gap by considering the full pipeline of the components which make up a route planner. Building the full system allows for evaluation of the final tool, but also generates insights for technical limitations and opportunities found during development. 

=== research steps
#todo(position: "inline")[step 2 is by far the biggest, change to match at the end/ maybe this section just gives double info]
In broad steps these are the stages the research went through:
1. A literature review was conducted to identify the functional requirements of the routing tool. This review informs the core components of the application, the role of SOLWEIG in the workflow, and the desired routing logic. It also establishes starting technical requirements with which the elements are evaluated.

2. The route planner is developed iteratively by treating its main stages as separate but connected design components. This allows each component to be designed, analysed, and refined before being integrated into the complete system. Here the emergent nature of the research leaves room for new requirements and directions of inquiry as the implementation develops.

3. As is common in DSR the resulting route planner is evaluated with regard to its utility and the requirements derived from the literature review. With utility being practical and goal oriented; how well does the tool do what it's supposed to do. And how well does it achieve the technical requirements.

4. The development process is reflected upon to identify key challenges, trade-offs, and effective implementation choices. These reflections are used to derive broader insights and practical recommendations for future UMC-informed routing applications. Which are (part of) the results of this thesis and described in that chapter.

=== Data & tools
For the creation of the tool a bounding box was chosen of a neighbourhood in Rotterdam with varying urban features: green & blue corridors, parks and different types of roads. As displayed in @fig:bbox the bounding box spans about 2.5 kilometers north and 2 kilometers east to west. This is to limit the calculation time for SOLWEIG and data download. An area of this size allows for in depth testing without great demands on runtime. 

#figure(
  image("../figs/methods/testing_area.png", width: 80%),
  caption: [
    Red bounding box area for testing
  ],
) <fig:bbox>
#table(
  columns: (1fr, auto, auto),
  inset: 10pt,
  align: horizon,
  table.header(
    [], [*left lower corner*], [*right top corner*],
  ),
  [WSG84 (lat/long)],
  [51°52'46.75"/4°27'39.74"],
  [51°53'48.48"/4°28'59.42"],
  [RDNEW],
  [(91229,432752)],
  [(92777,434641)]
)
- using data preparation from solfd
  - what does the input data look like and what datasources are used for it
- using SOLWEIG_GPU
- ERA5
- using DelftBlue
- OSM
- UMEP
== Development of the routeplanner 
#todo(position: "inline")[Relate to RQ's. Currently this is too seperate from them.]
// reason being: the sub RQ's as they are now are maybe a little too oriented on  the routeplanner as an outcome than the development of concrete recommendations.
To ensure the insights gathered in this thesis are as broadly applicable as possible, the components are developed and evaluated separately. In existing research there is a wide variety of methodologies, suggesting that there are multiple valid ways of building a tool like this. By separating the research into component-level design elements, the findings associated with each part can be applied flexibly in different methodological contexts.

Each component is framed as a problem–solution pair, where the problem statements are derived from approaches in existing literature and evaluating them against the desired software property of scalability. The proposed solutions are informed both by existing literature and by insights gained in earlier development stages.#todo[At the end: is this what I've actually done?] 

The final description in the methodology represents the state after the multiple design iterations. Where applicable the emergent design process is represented by tables showing initial approach, the bottleneck it introduced, and how the approach was revised. More information on these changes can be found in Appendix #todo[make more detailed tables]A. For some elements the initial direction and approach gathered from literature proved sufficient and no revision was necessary to come to the final product.

=== The pedestrian routing tool
==== Purpose & structure


The final tool is a pedestrian route planner that uses urban microclimate model outputs to generate thermally informed walking routes. Instead of calculating only the shortest route, the tool allows these modelled thermal conditions to influence the cost of walking along a certain road. This combines into a Dijkstra routing algorithm that chooses a least-cost route that balances heat exposure and distance.  

The tool has a modular structure, where separate components are all part of the pipeline that make up the pedestrian route planner (see @fig:tool). First, spatial input data are prepared for the selected study area. Consisting of the OSM pedestrian #todo[first mention of OSM but explained in next section?] network and the necessary SOLWEIG input data. Then SOLWEIG was run, which produces the UTCI, TMRT and shade maps per hour. These are linked to the OSM pedestrian network by assigning environmental values derived from the SOLWEIG output maps to the edges. Finally, the routing prototype has an algorithm that these weighted edges to calculate thermally conscious routes and a web-based display that allows the user to access the information.

Finally, the scalability of the tool was tested by running the entire pipeline for another area in rotterdam and evaluating the differences. #todo[More concretely describe these tests once they are done. ]

#figure(
  image("../figs/methods/tool_descrip.png", width: 100%),
  caption: [
    Overview of different tool modules
  ],
) <fig:tool>
==== Requirements
- describe requirements:
  - scalability 
  - performance
  - modularity
- component based design that supports reusability #todo[write this]
 
#table(
  columns: 3,
  table.header[*Initial approach*][*Bottleneck*][*Revised*],
  [Ease of use, performance, scalability],
  [strong coupling #footnote[Coupling is a term used in software design that describes how dependent software modules are on each other. High coupling means that changes in one module of the software can have big effects on other modules. Low coupling means that the modules are largely independent from each other.]  between components introduces performance bottlenecks],
  [modular system design with high cohesion #footnote[Cohesion is closely related to coupling and refers to how well all the elements in a module are supporting a single well defined purpose. For reusability low coupling and high cohesion is preferred.] that supports reusability],
)
=== Data preparation
The first component consisted of gathering the pedestrian network from the OSM and the input data for SOLWEIG. Existing research on thermally comfortable routing differs widely in how the input data is collected, and which data is considered in the first place. Largely constrained by data availability. The solution for this problem adopted in this thesis is to use UMC modelling which requires more simplistic input information. This makes the entire workflow more scalable.

==== UMEPIO
Monahan (2025) developed SOLFD which has an automated pipeline to gather all necessary input data that is needed to run SOLWEIG. However, this pipeline was only available as separate sections of code in a GitHub repository, so its practical reusability remained limited. To ensure scalability the collection and preparation of input data should require as little manual labour as possible. SOLWEIG requires several spatial input layers, including CHM, DSM, DTM and Landcover rasters. When these are collected and processed manually, the workflow becomes time-consuming and more vulnerable to human error.

#show link: underline
Which is why the pipeline in SOLFD was published as a pip package; #link("https://pypi.org/project/umepio/")[UMEPIO]. In addition to the reduction in manual effort (and the time that takes) and increased standardisation #todo[make connection more natural], publication in a pip package supports reusability in other contexts than a route planner. Supporting the design goals of scalability and reusability.


==== OSM to pedestrian network representation
*Not really discussed in existing research*

Two main data sources were considered for this step. The first option was OpenStreetMap, which is commonly used in routing research because it is open, widely available, and accessible through established tools such as OSMnx. The second option was Overture Maps, which provides cloud-native and normalised geospatial data and might be preferable in terms of scalability. #todo[maybe remove information about overture to the table in the appendix & the table above]

However, manual inspection of the study area showed that some less standard tags were lost in the Overture dataset. In particular for pedestrian infrastructure, sidewalk-related tags were lost. While sidewalk data in OpenStreetMap is not complete or consistently available, the presence of these tags can still improve the closeness of the representation to the real world. Since pedestrians do not use the center-lines of the road, but the sides. For this reason, retaining this information was considered more important than using a more normalised network source.

The final workflow therefore uses plain OpenStreetMap data, gathered through OSMnx #footnote[OSMnx is a python package that downloads OSM data into a NetworkX representation, allowing for easy access to the data.], as the basis for the transportation network. This choice makes it possible to preserve the sidewalk information. This decision is important because the pedestrian network is not only used for routing, but also for linking SOLWEIG outputs to the walking environment. The location of network edges influence which raster values are sampled so a close representation is crucial for a good representation. Keeping this information allows for further analysis and prevents unnoticed loss of detail.

A custom filtering was applied to gather the pedestrian network from the OSM since the OSMnx pedestrian filtering removed information, like the sidewalks that was necessary to keep. Additionally, OSMnx automatically adds two edges per node pair to indicate that both directions are accessible. This doubles the size of the network, which is why the network is saved as an undirected graph. Where very node pair is connected by a single bi-directional edge, almost halving the storage requirement. 

#table(
  columns: 3,
  table.header[*Initial*][*Bottleneck*][*Revised*],
  [Standard filtered OSMnx],
  [Loss of tags],
  [Personal pedestrian filtering],
  [Multiple ways to tag the same thing],
  [routing requires flattened representation, but we don't want to lose any information],
  [Add personal pedestrian tags],
  [Bi-directionality in standard representation enforced through double edges],
  [Redundant information increases storage demand],
  [Change network representation to undirected],
  [Centre lines],
  [Pedestrians do not use the center lines of the road],
  [Solution out of scope: provide analysis for future work],
)
=== UMEP execution
The central design requirement was scalability so running SOLWEIG introduced two main challenges:
- *Space:* UMEP outputs consist of large raster datasets (.tif) containing hourly values that depend on meteorological conditions. Storing these as they are for multiple meteorological situations and locations generates a gigantic storage demand.
- *Time:* The computational cost of running UMEP simulations is substantial, depending on the hardware it can take about 20-40 minutes to run a 3km by 3km square.

For these problems, two solutions were investigated. The first was a _generalist_ approach, in which UMEP would be run on demand. This would reduce storage requirements, since the collection of input data and running of the model would be done only when a route is requested. However, this shifts the bottleneck to input-data collection. If the full tile surrounding the route of input data still needs to be collected and stored, there is little advantage over storing the model outputs directly. Alternatively, collecting smaller tiles around the route would require many requests to an external data server, such as PDOK. This would greatly increase latency and create a dependency on an external source during route calculation. For a scalable route planner, this is undesirable because it makes the system slower and less reliable. #todo[Too much detail?--> can be a lot shorter.]

The second solution was a _specialist_ approach, in which UMEP outputs are precomputed for the study area and transformed before storage to become a manageable size. The computation time can then be moved to an external machine depending on hardware availability. This approach was chosen for this thesis. SOLWEIG\_GPU was run on the DelftBlue supercomputer which has multiple GPUs shared across the university. The performance (computation time) of SOLWEIG\_GPU was entirely dependent on the RAM available. With tests on the same GPU having either 10GB or 80GB of RAM produces computation times for the test area of 37 minutes or 18 minutes respectively. These large differences indicated that a full performance benchmark would not be additive to this research, since any further work would most likely have access to different hardware anyway. Tile size was not tested but determined using the information provided by the developers of SOLWEIG\_GPU @kamath_solweig-gpu_2026. #todo[should explain more/remove?] 

The output of SOLWEIG\_GPU consists of overlapping tiles, so these were merged back into one file. The tiles were merged back together halfway across the overlap, however there still sometimes are slight differences between the edges in values. So the when the tiles are stuck together the cells around the edges are normalized and averaged to prevent harsh lines. 

Different resolutions were tested and compared using a test set to see how the pedestrian network changes. Since a lower resolution will decrease the computation time. 

#todo(position: "inline")[Which extra days to include for weather(if any)]

#table(
  columns: 3,
  table.header[*Initial*][*Bottleneck*][*Revised*],
  [run umep on demand on small area],
  [gathering input data too slow],
  [methodological approach abandoned],
)
=== Integration within the pedestrian network
* not really discussed in research*
This component connects the SOLWEIG outputs to the pedestrian network, which is further referred to as network annotation. Which has both a technical and conceptual side#todo[good wording? try to say; within the context of thermal comfort/ inhoudelijk]. On the technical side this step needs to reduce the storage demands and define the network data structure to make it suitable for routing. Conceptually, this step abstracts away much of the detail which is captured in the full UTCI, TMRT and shadow maps. Since, for routing purposes, only a few values can be considered. Therefore, the attributes were chosen to preserve the aspects of the model outputs most relevant to thermal comfort and route choice.

To do this the raster outputs were sampled along the edges of the pedestrian network. Each edge was assigned summary attributes derived from the raster cells it intersects. In this way, the detailed SOLWEIG outputs were converted into edge-level attributes that could be used directly in the routing algorithm.

The algorithm does for every edge in the graph $G(V, E)$:
1. Get the geometry of the edge.
2. Find the indexes of all intersecting raster cells of this edge.
3. Sample all 24 bands for the intersecting cell.
4. Flatten these cells into one attribute to attach to the edge.
  - `utci_category`: took the median of all the UTCI values along an edge and mapped that to the corresponding category. 
  - `utci_median`#todo[Update when tests are complete]
#figure(
  table(
    columns: 2,
    table.header[*UTCI (deg C)*][*Thermal stress*],
    [> 46],
    [Extreme heat stress],
    [38 to 46],
    [Very strong heat stress],
    [32 to 38],
    [Strong heat stress],
    [26 to 32],
    [Moderate heat stress],
    [9 to 26],
    [No thermal stress],
    [0 to 9],
    [Slight cold stress],
    [-13 to 0],
    [Moderate cold stress],
    [-27 to -13],
    [Strong cold stress],
    [< -40 ],
    [Extreme cold stress]
  ), 
  caption: "UTCI categories as defined for SOLWEIG"
)<utci-categories>

Where the categories in @utci-categories represent increasingly high penalties to the edge weight. This is in line with findings from Basu et al. (2024), who found that higher UTCI categories have "non-uniform and possibly exponential" effect on perceived walking distance @basu_hot_2024. Using categories of an outdoor thermal comfort index to assign edge weights is consistent with the methodological approach of Ma et al. (2025), who applied PET-based categories for this purpose @ma_active_2025. In this thesis, UTCI was used instead of PET due to the absence of detailed wind information. Nevertheless, the underlying principle remains comparable, as both approaches translate thermal comfort categories into routing penalties.

To do the sampling efficiently the the SOLWEIG output was transformed to a file format suited to spatial access. The merged SOLWEIG output was saved to a .Zarr file, which is a cloud optimized file format that allows efficient access to multidimensional raster data (@sec:annotation). Because Zarr supports chunked access, only the relevant sections of the raster need to be loaded into memory during sampling. Additionally, in this chunk all the bands are present, so only a single query is needed. This is particularly suitable for network annotation, where each edge typically intersects only a small portion of the full raster. Compared with the previous .tif-based workflow, this reduced the annotation time from approximately five minutes to ten seconds. #todo[table?]

The annotated network is then saved to two geoparquet files one with all the edges and one with all the nodes, using a custom data schema. With the schema serving as the translation layer between the network representation used in the annotator and the router as described in @fig:network-schema. 
#figure(
  image("../figs/methods/network_schema.png", width: 80%),
  caption: [
    Shared network representation
  ],
) <fig:network-schema>
#figure(
table(
  columns: 3,
  table.header[*Initial*][*Bottleneck*][*Revised*],
  [Sample edge geometry from merged tif],
  [Multiple lookups for every band negatively impact performance],
  [Merge tif tiles in a .Zarr format],
  [Flatten environmental values to one attribute],
  [Large information loss, reduces explainability],
  [Add extra attributes that can help analyse the final routes],
  [Use OSMnx networkX representation],
  [Introduces performance issues during routing],
  [Shared data schema and storage in geoparquet, storing nodes, edges and metadata],
  ),
  caption: "Emergent process network annotation"
)<table-annotation>

=== Routing Prototype
problem: algorithm should be dynamic -> as a pedestrian walks the length of being in heat is increasingly bothersome.  Algorithm should not just have researcher defined weights, since the situation can change for different user preferences. -> user defined.
- Using weighted dijkstra?
- User defined 'importance' metrics -> 'do you wanna walk in the sun?'
- combining all components
==== Edge cost
- Environmental cost as a penalty to the length of the edge.
  - If only environmental cost is considered edge length a very hot edge of 5m will have a bigger cost than a slightly hot edge of 500m. So length should always factor in. Leadign to: 
  $C_e​=L_e​⋅(1+P_e​)$

  With:
  $C_e$: the cost of the edge \
  $L_e$: the length of the edge in meters \
  $P_e$: the normalized environmental penalty mulitplier \
Where $P_e$ is built using the user preferences, the environmental variable and the state of the pedestrian. Which is quantified in the following formula:

$P_e = sum_(i=1)^n w_i * gamma_i (s) * p_i$

with:\
$w$: being the user defined importance of a variable \
$gamma$: being the dynamic sensitivity function that depends on route-state $s$.\
$p$: the normalized envioronmental penalty on edge $e$\

The environmental penalty scales with the severity of the heat stress. With moderate heat stress contributing about 80m 


Application: not really problem, more of a tool for communication & testing.
- Prototype using Shiny
- Why API between routing and GUI


#figure(
table(
  columns: 3,
  table.header[*Initial*][*Bottleneck*][*Revised*],
  [NetworkX representation],
  [Performance issues at scale],
  [Custom network representation],
  [Application also does routing],
  [Coupling of elements can negatively effect reusability and client-side calculation of routes introduces performance constraints],
  [Separate routing from the application and communicate between the two via an API]
),
  caption: "Emergent process routing network"
)<table-routing>

== Validation and evaluation of the route planner (analysing the data)
<validation>
=== Evaluation
Runeson et al. note that insights from design-based research are inherently context based @runeson_design_2020. 
- functional validation: are outputs consistent, does it make sense in a pedestrian context. (this balance between level of detail etc) (evaluate routes/inputs)
- intended purpose evaluation: are the routes significantly different, does it scale, is it easy to use and extend. (evaluate as a tool)
- reflection on implementation choices: How do i come to recommendations

=== Validation
The design of the algorithm is informed by structural evaluation. The empirical validation was done by creating a stratified origin destination test set. In this test set there are meaningful categories of OD pairs that are expected to generate certain statistics when routes are generated between them. For example, the top area of the test area is very hot around mid day, so we expect longer routes that have to cross it to be longer on average than the same pairs during the night. This test set can then be compared to results gathered by previous work and the parameters of the algorithm and the weights in the pedestrian network can be tuned. 

These categories were derived manually based on the distribution of heat in the input dataset.

== Limitations of this study design
- No dataset to compare my routes to, no questionares to people that use them. 
- many assumptions on how the world behaves
- validation stratagy is limited and assumes that a lower temperature on the roads limits heat stress. 
- any recommendations flowing from this are generalized as much as possible but stay in the realm of a route planner based on urban microclimate modelling.


/*
Q's this chapter should answer in the end:
Why was a design-oriented approach chosen?
What role does the tool play in answering the research question?
What were the stages of development?
What data, inputs, and assumptions were used?
How was the tool tested or validated?
How were lessons drawn from the design process?

*/
/*
== Research design 
The methodology is structured around four main phases, which are shown in @fig:overview_method.
#figure(
  image("../figs/research_steps.png", width: 100%),
  caption: [
    The 4 phases of this research
  ],
) <fig:overview_method>

Explain the stages of the study, for example:
analyze SOLWEIG outputs and routing requirements
design a data transformation pipeline
implement the routing prototype
test and evaluate functionality, scalability, and usefulness
derive generalizable recommendations/framework
3.3 Data and case study
Describe:
study area
SOLWEIG outputs used
street network data
any demographic, meteorological, or comfort threshold data
software stack

3.4 Methods for transformation and integration
This is still methodology, not implementation in full technical detail.
Here you explain conceptually:
how microclimate rasters or grids are converted into routing cost information
how costs are linked to pedestrian network segments
how routing logic incorporates thermal comfort
what assumptions you make
3.5 Evaluation strategy
Very important. Explain how you assess whether your approach works.
For example:
technical feasibility
computational scalability
quality of routing outputs
interpretability or applicability of results
usefulness of the framework for others
== design rationale
=== umepio (standardisation of data preperation)
a modular, reproducible preprocessing component was required
- the existing pipeline was fragmented, hard to reproduce, or difficult to scale
-preparing SOLWEIG input data required multiple preprocessing steps that needed standardization
- a modular package was needed to support openness, repeatability, and later integration into the routing workflow
- packaging the pipeline was part of answering the research question, because data transformation is a necessary step between raw microclimate inputs and tertiary application outputs

=== running solweig (SOLWEIG_GPU)


This thesis has a design-based research approach, in which new insights will be generated through iterative design, implementation, and consequent evaluation of the functionalities. The final tool serves both as a result of the research and as a way to investigate strategies for integrating urban microclimate data into web-based routing applications.



== Data preparation <data-preparation>
#figure(
  image("../figs/data_prep_methods.png", width: 100%),
  caption: [
    The necessary input datasets per tool that will be used in this research, the pink colored data still needs to be implemented.
  ],
) <fig:data_prep>
The first step of this research is the collection and preparation of all datasets required to run SOLWEIG and URock. This is partially supported by SOLFD @solfd_githum, which provides an automated data collection pipeline for the Netherlands tailored to SOLWEIG. URock, however, requires additional specialized input data that is not currently supported by SOLFD. As part of this thesis, the existing SOLFD pipeline will therefore be extended to also collect and prepare the necessary inputs for URock. Also, the pedestrian network is prepared for integration with environmental attributes.

== Operationalization <operationalization>
The goal of this phase is to address RQ1 through iterative code development.
#quote[_What design strategies and data structures enable the effective use of UMEP outputs  in scalable web-based applications?_]
This approach is adopted because limited prior research exists on how to operationalize UMEP outputs for scalable, web-based applications. The central design requirement is scalability, meaning that the system should be easily extendable to larger spatial extents (e.g., additional cities).
Two primary challenges are identified:
- *Space:* UMEP outputs consist of large raster datasets (.tif) containing hourly values that depend on meteorological conditions.
- *Time:* The computational cost of running UMEP simulations is substantial.
#figure(
  image("../figs/oper_methods.png", width: 50%),
  caption: [
    Workflow iterative code development: operationalizing UMEP outputs
  ],
) <fig:oper_methods>
Using the workflow shown in Figure @fig:oper_methods, two approaches are investigated for feasibility, with the aim of identifying techniques and bottlenecks when deploying UMEP-based workflows in web-based services:
- *Generalist:* Running UMEP (partially) on demand reduces storage requirements, as only model inputs need to be retained. In this case, computation time becomes the primary bottleneck.
- *Specialist:* Reducing storage requirements in a use-case–specific manner by synthesizing UMEP outputs into the pedestrian network prior to publication. This approach trades generality for efficiency.
To support these approaches, SOLWEIG-GPU is used, as it can operate outside the QGIS environment and enables GPU-based acceleration where possible. URock will be adapted in this thesis to also run independently of QGIS. This improves extensibility, for example, when deploying on a Linux server, since QGIS is no longer needed. Based on these outputs, PET is calculated and used as an input for routing. The PET values can be evaluated against measurements done in Rotterdam. 

== Routing <routing>
This phase will answering RQ2 trough iterative code development and literature review.
#quote[How can established multi-objective routing algorithms incorporate UMEP outputs and be implemented and adapted to automatically generate heat aware pedestrian routes?]
In contrast to the operationalization (@operationalization) phase, a substantial body of literature exists on “pleasant” or heat-aware routing. Therefore, the workflow for addressing RQ2 begins with a synthesis of existing research rather than exploratory experimentation. 
#figure(
  image("../figs/routing_methods.png", width: 50%),
  caption: [
    Workflow iterative code development: routing
  ],
) <fig:routing_methods>
From the literature, two key requirements for the routing strategy are derived:
1. The algorithm should account for route length as a contributor to heat exposure, as demonstrated by Wen et al. and Rußig & Bruns @wen_walking_smart_2025 @rusig_reducing_2017.
2. The algorithm should avoid reliance on researcher-defined weights, as used in approaches such as Aliyev et al. @aliyev1_exploiting_2025 @aliyev2_vehicle-pedestrian_2025.

The first requirement reflects the fact that both the duration and intensity of pedestrian activity influence experienced heat stress. The second requirement is motivated by scalability and extensibility: calculating trade-offs statistically on a route-by-route basis reduces subjectivity and enables the routing problem to be formulated as an optimization problem. This formulation of the algorithm also allows the inclusion of additional environmental factors beyond heat in future extensions.

== Application <application>
In this phase the actual implementation will be created, in doing so the RQ3 will be answered.
#quote[What does scalability mean for a pedestrian routing tool particularly regarding its potential for spatial and functional extension?]
The insights obtained from data preparation, operationalization, and routing are integrated into a web-based pedestrian routing tool. This application serves as a demonstration of the proposed framework, enabling evaluation of data processing, routing behavior, and system performance. The interface is used to reflect on the feasibility, extensibility, and clarity of presenting UMEP microclimate information within a user-facing routing tool. The tool will be built on top of the existing open-source infrastructure of the OpenRouteService #footnote[https://openrouteservice.org].
#pagebreak()
= Preliminary results
<preliminary-results>
== Data preparation
Steps have been made to start the collection of input data automatically, using SOLFD @solfd_githum and SOLWEIG_GPU @solweig_gpu_git. SOLFD outputs the Landcover, CHM, DTM and DSM which are displayed in @fig:solfd-output. SOLWEIG_GPU outputs the TMRT map which is displayed in @fig:solweig-gpu-output.

#figure(
  image("../figs/solfd_outputs.png", width: 100%),
  caption: [
    Input datasets needed for SOLWEIG generated by SOLFD @solfd_githum.
  ],
) <fig:solfd-output>
#figure(
  image("../figs/SOLWEIG_GPU_output.png", width: 50%),
  caption: [
    TMRT output map from SOLWEIG_GPU at band 0. @solweig_gpu_git
  ],
) <fig:solweig-gpu-output>
== Literature review
Existing literature has been evaluated to determine the best algorithm to be implemented for the routing problem. Leading to the expectations described in the methods section (@routing)



#set page(
  paper: "a4",
  flipped: true,
)

= Time planning
<time-planning>
#figure(
  image("../figs/timeplanning.png", width: 100%),
  caption: [Time planning with coding tasks per week],
)

#set page(
  paper: "a4",
  flipped: false,
)

= Tools and datasets used
<tools-and-datasets-used>
== Data preparation
- SOLFD @solfd_githum generates:
  - DTM (digital terrain model (includes buildings & vegetation)), DSM (digital surface model (only the ground)), CHM (only vegetation), Landcover (based on bgt (basisregistratie grootschalige topografie)), building polygons
- Use the DTM, DSM, CHM, and building polygons to generate the input data for URock -> building polygons with height values and vegetation polygons with height values.
- Overture maps #footnote[https://overturemaps.org] for the pedestrian network. Will be evaluated against just using Open Street Map data.

== Operationalization
- UMEP
  - SOLWEIG_GPU @solweig_gpu_git, stand alone python package that implements a sped-up version of SOLWEIG.
  - URock @bernard_urock_2023, currently implemented in UMEP-processing.
  - PET @lindberg_urban_2017 generator currently implemented in UMEP, uses outputs from SOLWEIG and URock.
== Routing
For routing, a tool like graphHopper or the OpenRouteService can be explored, since both implement an API to generate routes between cities. This is probably not necessary for the tool now, since it's only in one city.
== Application
OpenRouteService #footnote[https://openrouteservice.org]: open-source route planning tool implementing both a front-end and back-end. This was already used for pleasant routing by Foshag et al. (2024) and Novack et al. (2018) @foshag_how_2024 @novack_system_2018. GraphHopper also has an associated front-end, so this can also be explored.
*/