#import "../template.typ": *

= Methodology
<chap:methodology>
#todo(position: "inline")[*This chap should answer: what did I do as a research process, what does the tool look like and how did I evaluate everything*]
This section first describes the research approach, which contextualizes the method used in this thesis. Secondly, the study itself is described in large(r) steps. Then the data and tools which were used are described. Finally, the separate software components of the final are described.
 
== Research approach (contextualize study method
<research-approach>
This thesis adopts a Design Science Research (DSR) methodology in which knowledge is generated through the iterative design, implementation, and evaluation of an artefact @runeson_design_2020 @wohlin_design_2021. Here that artefact is a open-source pedestrian routing tool that uses UMEP outputs to generate routes that avoid heat stress #todo[ensure consistency with rest of thesis]. The final tool serves both as a result of the research and as a way to investigate strategies for integrating urban microclimate data into web-based routing applications. To ensure that the design process yields generalizable insights, systematic evaluation is conducted throughout all stages of development @van_rensburg_model_2019.

@fig:methods shows how reflexive DSR is applied in this thesis. 
#figure(
  image("../figs/methods/methods_diagram.png", width: 80%),
  caption: [
    Overview methodological approach
  ],
) <fig:methods> 

First literature is used to conceptualize the problem and identify the main design requirements. Then a solution is designed, which is validated according to the previously defined requirements. After which reflexive evaluation is used to readjust the problem conceptualization and requirements for the next design iteration. 

This process reflects the practical orientation of design science research for software engineering. Where the contribution of the research stems from its ability to solve a problem @runeson_design_2020. This idea is encompassed in the concept of utility, as described by Hevner et al.:_“If the artifact does not solve the problem (search, implementability), it has no utility. If utility is not demonstrated (evaluation), then there is no basis upon which to accept the claims that it provides any contribution”_ @hevner_utility_2004.

Utility is not only achieved through formal validation against predefined requirements, but also through insights generated by the iterative process with which the final tool is built. To place these insights into context we need to explicitly mention the role of the researcher/designer. The tool is designed through a "sequence of expert activities" @hevner_utility_2004, so even design iterations that were later upended can teach us something about how these systems are usually developed. In social sciences Finlay (2002) describes this position as "where researchers engage in explicit, self-aware analysis of their own role" and calls this reflexivity @finlay_outing_2002. In this thesis it's explicitly acknowledged that the expertise of the researcher shapes both the final tool but also the direction of inquiry. And draws generalized lessons not just from the final tool, but also the entire process of inquiry. Acknowledging that the fact that the researcher (who has expertise) decided on a course of action provides information on how assumptions and descriptions from previous research can shape the initial problem conceptualizations and implementation choices. #todo[paragraph might be too vague]

The iterative design process makes this research emergent; "Emergent design involves data collection and analysis procedures that can evolve over the course of a research project in response to what is learned in the earlier parts of the study"  @morgan_emergent_2008. This means that insights gained during the process can change the process itself and are expected to shape the direction of inquiry. 

== Describe the study (document the research process)
<research-steps>
Existing research has shown the possibility and usefulness of thermally informed routing @foshag_how_2024 @ma_active_2025 @rusig_reducing_2017 @wen_walking_smart_2025, but paid less attention to the technical foundations. This thesis addresses this gap by considering the full pipeline of the components which make up a pedestrian route planner that generates thermally comfortable routes. Building the full system allows for evaluation of the final tool, but also generates insights for technical limitations and opportunities found during development. 

=== research steps
#todo(position: "inline")[step 2 is by far the biggest, change to match at the end/ maybe this section just gives double info]
In broad steps these are the stages the research went through:
1. A literature review was conducted to identify the functional requirements of the tool. This review informs the core components of the application, the role of SOLWEIG in the workflow, and the desired routing logic. It also establishes starting technical requirements with which the elements are validated.

2. The route planner is developed iteratively by treating its main stages as separate but connected design components. This allows each component to be designed, analysed, and refined before being integrated into the complete system. Here the emergent nature of the research leaves room for new requirements and directions of inquiry as the implementation develops.

3. As is common in DSR the resulting route planner is evaluated with regard to its utility and the requirements derived from the literature review. With utility being practical and goal oriented; how well does the tool do what it's supposed to do. And how well does it achieve the technical requirements.

4. The development process is reflected upon to identify key challenges, trade-offs, and effective implementation choices. These reflections are used to derive broader insights and practical recommendations for future UMC-informed routing applications. Which are (part of) the results of this thesis and described in that chapter.

=== Data & tools
For the creation of the tool a bounding box was chosen of a neighbourhood in Rotterdam with varying urban features: green & blue corridors, parks and different types of roads. As displayed in @fig:bbox the bounding box spans about 2.5 kilometres north and 2 kilometres east to west. This is to limit the calculation time for SOLWEIG and data download. An area of this size allows for in depth testing without great demands on runtime. 

#figure(
  image("../figs/methods/testing_area.png", width: 80%),
  caption: [
    Red bounding box area for testing
  ],
) <fig:bbox>
#table(
  columns: (1fr, auto, auto),
  inset: 10pt,
  align: horizon,
  table.header(
    [], [*left lower corner*], [*right top corner*],
  ),
  [WSG84 (lat/long)],
  [51°52'46.75"/4°27'39.74"],
  [51°53'48.48"/4°28'59.42"],
  [RDNEW],
  [(91229,432752)],
  [(92777,434641)]
)
- *SOLFD @monahan_cool_2025: * Pipeline for generating all the input necessary to run SOLWEIG when given only a bounding box. 
- *ERA5: * European weather model that provides the weather information needed by SOLWEIG.
- *SOLWEIG @lindberg_urban_2017: * Urban microclimate model that estimates thermal comfort on a micro scale.
- *SOLWEIG_GPU @kamath_solweig-gpu_2026: * Implementation of SOLWEIG @lindberg_urban_2017 on GPU that achieves speed-up in terms of computation time.

- *DelftBlue @DHPC2024: * high performance supercomputer TU Delft that was used to do the SOLWEIG_GPU runs.
- *Open Street Map (OSM) @osmnx_geoff_2025: * #todo[add citation of specific OSM map used] Base map used for the pedestrian network.
- *UMEP @lindberg_urban_2017: * Urban Multi-scale Environmental Predictor, open-source tool that houses SOLWEIG and other "city-based climate services" @lindberg_urban_2017. 
== Development of the routeplanner 
#todo(position: "inline")[Relate to RQ's, too separate from them?]
// reason being: the sub RQ's as they are now are maybe a little too oriented on  the routeplanner as an outcome than the development of concrete recommendations.
To ensure the insights gathered in this thesis are as broadly applicable as possible, the components are developed and evaluated separately. In existing research there is a wide variety of methodologies, suggesting that there are multiple valid ways of building a tool like this. By separating the research into component-level design elements, the findings associated with each part can be applied flexibly in different methodological contexts.

// Each component is framed as a problem–solution pair, where the problem statements are derived from approaches in existing literature and evaluating them against the desired software property of scalability. The proposed solutions are informed both by existing literature and by insights gained in earlier development stages.#todo[At the end: is this what I've actually done?] 

The description in the methodology represents the state after the multiple design iterations. Where applicable the emergent design process is represented by tables showing initial approach, the bottleneck it introduced, and how the approach was revised. More information on the emergent process can be found in @appendix-A#todo[make more detailed tables and move to appendix]. For some elements the initial direction and approach gathered from literature proved sufficient and no revision was necessary to come to the final product.

=== The pedestrian routing tool
The final tool is a pedestrian route planner that uses urban microclimate model outputs to generate thermally comfortable walking routes. Instead of calculating only the shortest route, the tool allows modelled thermal conditions to influence the cost of walking along a certain road. This combines into a Dijkstra routing algorithm that chooses a least-cost route that balances thermal comfort and distance. #todo[p. provides context, but maybe double info]

The tool has a modular structure, where separate components are all part of the pipeline that make up the pedestrian route planner (see @fig:tool). First, spatial input data are prepared for the selected study area. Consisting of the OSM pedestrian network and the necessary SOLWEIG input data. Then SOLWEIG was run, which produces the UTCI, TMRT and shade maps per hour. These are linked to the OSM pedestrian network by assigning environmental values derived from the SOLWEIG output maps to the edges. Finally, the routing prototype has an algorithm that these weighted edges to calculate thermally conscious routes and a web-based display that allows the user to access the information. 

Finally, the scalability of the tool was tested by running the entire pipeline for another area in rotterdam and evaluating the differences. #todo[More concretely describe these tests once they are done. ]

#figure(
  image("../figs/methods/tool_descrip.png", width: 100%),
  caption: [
    Overview of different tool modules.
  ],
) <fig:tool>
==== Requirements
The central design requirement for the tool is scalability. Existing heat-aware routing methods show that thermally informed routing is possible, but often remain limited to specific study areas. This makes it difficult to apply the same method to larger areas, different cities, or other environmental settings. In this thesis, scalability is therefore considered not only for the final route planner, but for every component in the pipeline.

Performance is treated both as part of scalability and as a requirement in itself. In a computationally inefficient tool existing bottlenecks will be amplified as it scales. At the same time, performance is also important for usability. The routing component should be able to generate routes within a reasonable time, especially when users interactively change origins, destinations, timesteps, or preference settings. 

Additionally, faster components make iterative development, testing, and debugging more efficient, while also improving the scalability of the complete workflow. However, performance optimization is not treated as an objective in itself. Optimization decisions are weighed against their expected impact on the use case, in order to avoid over-engineering individual components where the practical benefit would be limited.

Reusability is the third requirement and is addressed through a component-based architecture @khalid_software_2025 @mehboob_reusability_2021. #todo[explain why component based design supports reusability] The tool is divided into separate modules with low coupling #footnote[Coupling is a term used in software design that describes how dependent software modules are on each other. High coupling means that changes in one module of the software can have big effects on other modules. Low coupling means that the modules are largely independent from each other.] and high cohesion #footnote[Cohesion is closely related to coupling and refers to how well all the elements in a module are supporting a single well defined purpose. For reusability low coupling and high cohesion is preferred.]. Each component should have a clearly defined purpose and communicate with other components through explicit data formats if necessary. This makes the system easier to test, replace, or extend without changing the entire pipeline. Reusability also supports scalability, because future applications are unlikely to require the full methodology exactly as developed in this thesis. Depending on the available data, computational resources, and research aim, only specific components may be relevant. A modular design allows these individual parts to remain useful even when the complete route planner is not implemented.
#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial approach*][*Bottleneck*][*Revised*],
  [I9],
  [Ease of use, performance, scalability],
  [strong coupling between components introduces performance bottlenecks],
  [modular system design with high cohesion that supports reusability],
), caption: "Emergent process full tool")<tab:full-tool>
=== Data preparation
The first component consisted of gathering the pedestrian network from the OSM and the input data for SOLWEIG. Existing research on thermally comfortable routing differs widely in how the input data is collected, and which data is considered in the first place. Largely constrained by data availability. The solution for this problem adopted in this thesis is to use UMC modelling which requires more simplistic input information. This makes the entire workflow more scalable.#todo[unclear section, repetitive?]

==== UMEPIO
Monahan (2025) @monahan_cool_2025 developed SOLFD which has an automated pipeline to gather all input data that is needed to run SOLWEIG. However, this pipeline was only available as separate sections of code in a GitHub repository, so its practical reusability was limited. To ensure scalability the collection and preparation of input data should require as little manual labour as possible. SOLWEIG requires several spatial input layers, including CHM, DSM, DTM and Landcover rasters. When these are collected and processed manually, the workflow becomes time-consuming and more vulnerable to human error.

#show link: underline
Which is why the pipeline in SOLFD was published as a pip package; #link("https://pypi.org/project/umepio/")[UMEPIO]. In addition to the reduction in manual effort (and the time that takes) and increased standardisation #todo[make connection more natural], publication in a pip package supports reusability in other contexts than a route planner. 

==== OSM to pedestrian network representation

Two main data sources were considered for this step. The first option was OpenStreetMap, which is commonly used in routing research because it is open, widely available, and accessible through established tools such as OSMnx. The second option was Overture Maps, which provides cloud-native and normalised geospatial data and might be preferable in terms of scalability. #todo[remove information about Overture, not relevant enough?]

However, manual inspection of the study area showed that some less standard tags were lost in the Overture dataset. In particular for pedestrian infrastructure, sidewalk-related tags were lost. While sidewalk data in OpenStreetMap is not complete or consistently available, the presence of these tags can still improve the closeness of the representation to the real world. Since pedestrians do not use the center-lines of the road, but the sides. For this reason, retaining this information was considered more important than using a more normalised network source.

The final workflow therefore uses plain OpenStreetMap data, gathered through OSMnx #footnote[OSMnx is a python package that downloads OSM data into a NetworkX representation, allowing for easy access to the data.], as the basis for the transportation network. This choice makes it possible to preserve the sidewalk information. The pedestrian network is not only used for routing, but also for linking SOLWEIG outputs to the walking environment. The location of network edges influence which raster values are sampled so a close representation of the real world is important. Keeping this information allows for further analysis and prevents unnoticed loss of detail.

A custom filtering was applied to gather the pedestrian network from the OSM since the OSMnx @osmnx_geoff_2025 pedestrian filtering removed information, like the sidewalks that was necessary to keep. Additionally, OSMnx automatically adds two edges per node pair to indicate that both directions are accessible. This doubles the size of the network, which is undesired in this use case due to the annotation of the edges looping over every edge (see @mth:annotation). So the network is saved as an undirected graph. Where very node pair is connected by a single bi-directional edge, almost halving the storage requirement. 
#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I1],
  [Use the SOLFD pipeline directly from its original code distribution],
  [The pipeline was difficult to install and run because of how the code was distributed],
  [Distribute the SOLFD pipeline as a PyPI package],
  [I3],
  [Standard filtered OSMnx],
  [Loss of tags],
  [Personal pedestrian filtering],
  [I3],
  [Multiple ways to tag the same thing],
  [routing requires flattened representation, but we don't want to lose any information],
  [Add personal pedestrian tags],
  [I4],
  [Bi-directionality in standard representation enforced through double edges],
  [Redundant information increases storage demand],
  [Change network representation to undirected],
  [I2],
  [Centre lines],
  [Pedestrians do not use the center lines of the road],
  [Solution out of scope: provide analysis for future work],
),
caption: "Emergent process data preparation"
)
=== UMEP execution
For scalability running SOLWEIG introduced two main challenges:
- *Space:* UMEP outputs consist of large raster datasets (.tif) containing hourly values that depend on meteorological conditions. Storing these for multiple meteorological situations and locations generates a gigantic storage demand.
- *Time:* The computational cost of running UMEP simulations is substantial, depending on the hardware it can take about 20-40 minutes to run a 2km by 2km square at 0.5 resolution.

For these problems, two solutions were investigated. The first was a _generalist_ approach, in which UMEP would be run on demand. This would reduce storage requirements, since the collection of input data and running of the model would be done only when a route is requested. However, this shifts the bottleneck to input-data collection. If the full tile surrounding the route of input data still needs to be collected and stored, there is little advantage over storing the model outputs directly. Alternatively, collecting smaller tiles around the route would require many requests to an external data server, such as PDOK. This would greatly increase latency and create a dependency on an external source during route calculation. For a scalable route planner, this is undesirable because it makes the system slower and less reliable. #todo[Too much detail?--> can be a lot shorter.]

The second solution was a _specialist_ approach, in which UMEP outputs are precomputed for the study area and transformed before storage to become a manageable size. The computation time can then be moved to an external machine depending on hardware availability. This approach was chosen for this thesis. SOLWEIG\_GPU was run on the DelftBlue supercomputer which has multiple GPUs shared across the university. The performance (computation time) of SOLWEIG\_GPU was entirely dependent on the RAM available. With tests on the same GPU having either 10GB or 80GB of RAM produces computation times for the test area of 37 minutes or 18 minutes respectively. These large differences indicated that a full performance benchmark would not be additive to this research, since any further work would most likely have access to different hardware anyway. Tile size was not tested but determined using the recommendations provided by the developers of SOLWEIG\_GPU @kamath_solweig-gpu_2026. #todo[should explain more/move to implementation chp] 

The output of SOLWEIG\_GPU consists of overlapping tiles, so these were merged back into one file. The tiles were merged back together halfway across the overlap, however there still sometimes are slight differences between the edges in values. So the when the tiles are stuck together the cells around the edges are normalized and averaged to prevent harsh lines. 

Different resolutions were tested and compared using a test set to see how the pedestrian network changes. Since a lower resolution will decrease the computation time. 

#todo(position: "inline")[Which extra days to include for weather(if any)]
#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I5],
  [Run umep on demand on small area],
  [Gathering input data too slow],
  [methodological approach abandoned],
  [I6],
  [Use external compute infrastructure],
  [Performance depended strongly on available hardware],
  [Do tests on the available hardware before defining the workflow],
),
caption: "Emergent process UMEP execution"
)
=== Integration within the pedestrian network
<mth:annotation>
This component connects the SOLWEIG outputs to the pedestrian network, which is further referred to as network annotation. Which has both a technical and conceptual side#todo[good wording? try to say; within the context of thermal comfort/ inhoudelijk]. On the technical side this step needs to reduce the storage demands and define the network data structure to make it suitable for routing. Conceptually, this step abstracts away much of the detail which is captured in the full UTCI, TMRT and shadow maps. Since, for routing purposes, only a few values can be considered. Therefore, the attributes were chosen to preserve the aspects of the model outputs most relevant to thermal comfort and route choice.

To do this the raster outputs were sampled along the edges of the pedestrian network. Each edge was assigned summary attributes derived from the raster cells it intersects. In this way, the detailed SOLWEIG outputs were converted into edge-level attributes that could be used directly in the routing algorithm.

The algorithm does for every edge in the graph $G(V, E)$:
1. Get the geometry of the edge.
2. Find the indexes of all intersecting raster cells of this edge.
3. Sample all 24 bands for the intersecting cell.
4. Flatten these cells into one attribute to attach to the edge.
  - `utci_category`: took the median of all the UTCI values along an edge and mapped that to the corresponding category. 
  - `utci_median`#todo[Update when tests are complete]
#figure(
  table(
    columns: 2,
    table.header[*UTCI (deg C)*][*Thermal stress*],
    [> 46],
    [Extreme heat stress],
    [38 to 46],
    [Very strong heat stress],
    [32 to 38],
    [Strong heat stress],
    [26 to 32],
    [Moderate heat stress],
    [9 to 26],
    [No thermal stress],
    [0 to 9],
    [Slight cold stress],
    [-13 to 0],
    [Moderate cold stress],
    [-27 to -13],
    [Strong cold stress],
    [< -40 ],
    [Extreme cold stress]
  ), 
  caption: "UTCI categories as defined for SOLWEIG"
)<utci-categories>

Where the categories in @utci-categories represent increasingly high penalties to the edge weight. This is in line with findings from Basu et al. (2024), who found that higher UTCI categories have "non-uniform and possibly exponential" effect on perceived walking distance @basu_hot_2024. Using categories of an outdoor thermal comfort index to assign edge weights is consistent with the methodological approach of Ma et al. (2025), who applied PET-based categories for this purpose @ma_active_2025. In this thesis, UTCI was used instead of PET due to the absence of detailed wind information. Nevertheless, the underlying principle remains comparable, as both approaches translate thermal comfort categories into routing penalties.

To do the sampling efficiently the the SOLWEIG output was transformed to a file format suited to spatial access. The merged SOLWEIG output was saved to a .Zarr file, which is a cloud optimized file format that allows efficient access to multidimensional raster data (See @fig:zarr) #todo[reference to zarr section]. Because Zarr supports chunked access, only the relevant sections of the raster need to be loaded into memory during sampling. Additionally, in this chunk all the bands are present, so only a single query is needed. This is particularly suitable for network annotation, where each edge typically intersects only a small portion of the full raster. #todo[move Zarr expl to implementation] Compared with the previous .tif-based workflow, this reduced the annotation time from approximately five minutes to ten seconds. #todo[table?]

The annotated network is then saved to two GeoParquet files one with all the edges and one with all the nodes, using a custom data schema. With the schema serving as the translation layer between the network representation used in the annotator and the router as described in @fig:network-schema. OSMnx could only be saved as a graphGML, which can be difficult to parse and takes uup a lot of space. The network saved as a graphGML took up 26MB of space while GeoParquet only takes up 1MB of space.#todo[fit this i n more logically] 
#figure(
  image("../figs/methods/network_schema.png", width: 80%),
  caption: [
    Shared network representation
  ],
) <fig:network-schema>
#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I7],
  [Sample edge geometry from merged tif],
  [Multiple lookups for every band negatively impact performance],
  [Merge tif tiles in a .Zarr format],
  [I8],
  [Use OSMnx networkX representation],
  [Introduces performance issues during routing],
  [Shared data schema and storage in geoparquet, storing nodes, edges and metadata],
  ),
  caption: "Emergent process network annotation"
)<table-annotation>

=== Routing Prototype

This component uses the annotated pedestrian network both for visualization in the front-end and for applying the routing algorithm in the back-end. The front-end and back-end communicate through an API, which supports the broader requirement of reusability. Separating these components prevents the routing logic from becoming dependent on the interface. This is especially relevant at larger spatial scales, where executing routing operations directly in the front-end could introduce performance constraints. Since client-side set-ups are usually not configured for large calculations. #todo[is this clear?]

The network is loaded from the shared `NetworkSchema` and converted into a node-edge representation using NumPy, while maintaining an adjacency list for efficient graph traversal. his representation was selected because it is conceptually transparent and computationally efficient for the pedestrian routing tasks.#todo[more detail in implementation chapter]

A substantial body of literature exists on “pleasant” or heat-aware routing. So the requirements for the routing algorithm gathered from literature were quite good. In line with previous work the algorithm is an implementation of weighted Dijkstra @rusig_reducing_2017 @wen_walking_smart_2025 @aliyev1_exploiting_2025 @aliyev2_vehicle-pedestrian_2025 @ma_active_2025. With the algorithm having the following two characteristics:
1. The algorithm should account for both the intensity and duration of heat exposure during walking, as demonstrated by Wen et al. (2025) and Rußig & Bruns (2017) @wen_walking_smart_2025 @rusig_reducing_2017.
2. The routing process should not rely solely on researcher-defined weights, as this would impose fixed assumptions about the relative importance of environmental factors. Instead, it should incorporate user-defined environmental preferences, similar to the approach proposed by Novack et al. (2018) @novack_system_2018. 

The first requirement reflects that experienced thermal discomfort is cumulative and dynamic. Heat stress is not only determined by the conditions on an individual street segment, but also by the exposure accumulated along the route. For example, as pedestrians traverse multiple hot segments consecutively, the demand for cooler or shaded streets increases. This means that the cost of traversing an edge is partly dependent on the previously travelled edges.

The second requirement is motivated by the usability of the tool. Instead of only imposing fixed researcher-defined trade-offs between route length and thermal comfort, users are able to indicate their own preferences. This allows the routing behaviour to adapt to different pedestrian needs and weather conditions, without complex daily considerations. #todo[do i actually have extra weather conditions?]

==== Edge cost calculation
Each edge in the pedestrian network receives a generalized cost:
#set align(center)
  $C_e​=L_e​⋅(1+P_e​)$

#set align(left)
where $C_e$ is the edge cost, $L_e$ is the edge length in meters and $P_e$ is the normalized environmental penalty multiplier. This formulation ensures that route length always remains part of the optimization problem. For example, extremely hot but short edges may still be preferable to substantially longer detours, while longer exposure on moderately hot routes should still be captured.

The environmental penalty is defined as:
#set align(center)
  $P_e = sum_(i=1)^n w_i  * p_i * gamma_i (s)$
#set align(left)
where $w_i$ represents the user-defined importance of environmental variable $i$, 
$p_i$ is the normalized environmental penalty associated with edge $e$ and variable $i$,
and $gamma_i(s)$ is a dynamic sensitivity function dependent on the route-state $s$. 

The environmental penalty scales with the severity of the heat stress @basu_hot_2024. These multipliers effectively increase the distance of hot edges, which makes the algorithm more likely to choose a slightly longer route that is more comfortable. 

#figure(
  table(
  columns: (2fr, 1fr),
  inset: 8pt,
  stroke: 0.5pt,
  align: (left, center),

  [*Heat stress*], [*Multiplier*],
  [No thermal stress], [0.00],
  [Moderate heat], [0.10],
  [Strong heat], [0.35],
  [Very strong heat], [1.00],
  [Extreme heat / near-avoid], [3.00],
  ), 
  caption: [Heat stress categories and their associated penalty multipliers used in the routing algorithm.]
)<tab:heat_multipliers>

The application was developed in a fully Python-based environment as a tool for communicating and testing the routing logic. Since numerous front-end frameworks and implementation strategies could have been used, detailed exploration of front-end development was considered outside the scope of the research. Due to its limited relevance to the research question. The front-end was therefore deployed as a prototype, while remaining separated from the routing logic. This ensures that the routing component and the broader processing pipeline remain reusable for other applications.

The interface uses a MapLibre GL map #footnote[https://maplibre.org/projects/gl-js/], on which the pedestrian network can be displayed for each hourly timestep. A separate page allows the user to select two points on the map, choose a timestep, and adjust their preference settings. The generated route is then displayed on the map.

#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I8],
  [NetworkX representation],
  [Performance issues at scale],
  [Custom network representation],
  [I9],
  [Application also does routing],
  [Coupling of elements can negatively effect reusability and client-side calculation of routes introduces performance constraints],
  [Separate routing from the application and communicate between the two via an API]
),
  caption: "Emergent process routing network"
)<table-routing>

== Validation and evaluation of the route planner 
<validation>
In this thesis there is a distinction between validation and evaluation. Validation refers to testing the more standard functionality of the route planner. While evaluation encompasses the reflexive method used to generate the generalizable insights from the design iterations. The evaluation method was described in @research-approach and an overview with the insights can be found in @appendix-A. #todo[table is in next chapter. will probably be appendix in the end (and is still incomplete).]

The final pedestrian routing tool was validated on it's functionality. Does the tool actually generate routes that are more comfortable than the shortest path. First, two routes with a large difference between the shortest and most comfortable path were manually evaluated. This evaluation is done using the original SOLWEIG output maps to validate that the flattening is not causing any meaningful data loss or changes. This method is less structured, but aligns with how validation was happening naturally during the development process. 

Secondly, a more structured validation was performed. This method was used for final validation, but also for tuning the variable weights and attribute choices in the algorithm. For this a stratified origin destination test set was created. The test set contains meaningful categories of Origin-Destination (OD) pairs. These categories were derived manually based on the distribution of heat in the input data set. The categories are expected to generate certain statistics when routes are generated between the pairs. For example, the top area of the test area is very hot around mid day, so we expect routes that have to cross it to be longer on average than the same pairs during the night. Following the distribution of the UTCI (see @fig:utci-15) the categories are:
- `baseline_control`: medium distance paths in the lower half of the area, which has an (almost) constant UTCI.
  - Very little difference between shortest and comfortable path.
- `top_area_crossing`: paths that cross the entire area and cross the hot section above.
  - Average difference between shortest and most comfortable, should be higher than `long_cross_map`.
- `hot_zone_edge`: paths surrounding and crossing the hot area above.
  - Test set should show the largest differences.
- `long_cross_map`: paths covering the entire length of the tested area.
  - Slight difference between shortest and most comfortable (most of route is in constant zone).
- `short_hot_local`: short paths through the hot area.
  - Very little difference between shortest and most comfortable path. Tests whether the algorithm overcompensates and creates very long routes to avoid one or a couple of very hot edges. 

Plot of OD pairs in @fig:OD_pairs.

#figure(
  image("../figs/methods/UTCI_15.png", width: 80%),
  caption: [
    UTCI test area at 15:00
  ],
) <fig:utci-15> 

This validation serves more as a sensibility#todo[right word?] test than a true validation of thermal comfort along the routes. The validation aims to show that the thermally comfortable routes are notably different from the shortest path; in distance and average temperature. But also that the algorithm behaves in a predictable way for different types of routes. However, due to the levels of abstraction a true validation of thermal comfort would most likely require actual human participation to walk along the routes. Which is outside the scope of this research.#todo[should be discussion maybe?]
#set page(
  paper: "a4",
  flipped: true,
)
#figure(
  grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 8pt,

    image("../figs/methods/OD_pairs/baseline_control.png", width: 100%),
    image("../figs/methods/OD_pairs/top_area_crossing.png", width: 100%),
    image("../figs/methods/OD_pairs/hot_zone_edge.png", width: 100%),
    image("../figs/methods/OD_pairs/long_cross_map.png", width: 100%),
    image("../figs/methods/OD_pairs/short_hot_local.png", width: 100%),
    
  ),
  caption: [The five categories of OD pairs.]
) <fig:OD_pairs>
#set page(
  paper: "a4",
  flipped: false,
)