#import "../template.typ": *

= Methodology
<chap:methodology>
This section first outlines the research approach, contextualising the methodological choices made in this thesis. It then presents the study design in a series of larger methodological steps, followed by a description of the data sources and tools used. Finally, the individual software components that together form the final routing tool are described.
 
== Research approach
<research-approach>
This thesis adopts a Design Science Research (DSR) methodology in which knowledge is generated through the iterative design, implementation, and evaluation of an artefact @runeson_design_2020 @wohlin_design_2021. Here that artefact is an open-source pedestrian routing tool that integrates UMEP outputs to generate a thermally conscious route alternative to the shortest path. The final tool serves both as a result of the research and as a way to investigate strategies for integrating urban microclimate data into a pedestrian routing application. To ensure that the design process yields generalizable insights, systematic evaluation is conducted throughout all stages of development @van_rensburg_model_2019.


#figure(
  image("../figs/methods/methods_diagram.png", width: 80%),
  caption: [
    Overview methodological approach
  ],
) <fig:methods> 

@fig:methods shows how this iterative development is applied in this thesis. First literature is used to conceptualize the problem and identify the main design requirements. Then a solution is designed, which is validated according to the previously defined requirements. After which reflexive evaluation is used to readjust the problem conceptualization and requirements for the next design iteration. 

This process reflects the practical orientation of design science research for software engineering. Where the contribution of the research stems from its ability to solve a problem @runeson_design_2020. This idea is encompassed in the concept of utility, as described by Hevner et al.:_“If the artifact does not solve the problem (search, implementability), it has no utility. If utility is not demonstrated (evaluation), then there is no basis upon which to accept the claims that it provides any contribution”_ @hevner_utility_2004.

Utility is not only achieved through formal validation against predefined requirements, but also through insights generated by the iterative process with which the final tool is built. This aligns with the notion of emergent design, in which methodological choices are allowed to develop in response to findings that arise during the research process.  @morgan_emergent_2008. This means that insights gained during the process can change the process itself and are expected to shape the direction of inquiry. 

== Study Design
<research-steps>
Existing research has shown the possibility and usefulness of thermally informed routing @foshag_how_2024 @ma_active_2025 @rusig_reducing_2017 @wen_walking_smart_2025, but paid less attention to the technical foundations. To address this gap, this thesis considered the full workflow from microclimate modelling to route generation. This structure makes it possible to assess both the utility of the final route planner and the technical requirements of the individual components on which it depends.

=== Stages
1. A literature review was conducted to identify the functional requirements of the tool. This review informs the core components of the application, the role of SOLWEIG in the workflow, and the desired routing logic. It also establishes starting technical requirements with which the elements are validated.

2. A testing area was chosen in Rotterdam for which the prototype was developed.

3. The route planner is developed iteratively by treating its main stages as separate but connected design components. This allows each component to be designed, analysed, and refined before being integrated into the complete system. Here the emergent nature of the research leaves room for new requirements and directions of inquiry as the implementation develops.

3. The resulting route planner is evaluated with regard to its utility and the requirements derived from the literature review. With utility being practical and goal oriented; how well does the tool do what it's supposed to do. And how well does it achieve the technical requirements.

4. The development process is reflected upon to identify key challenges, trade-offs, and effective implementation choices. These reflections are used to derive broader insights and practical recommendations for future UMC-informed routing applications. 

=== Study area
For the creation of the tool, a bounding box was chosen in a neighbourhood in Rotterdam with varying urban features, including green and blue corridors, parks, and different types of roads. These features are relevant because urban morphology and greenery can influence pedestrian-level thermal conditions. In particular, the presence of trees, open spaces, water, and different street geometries makes this  area suitable for testing whether the routing tool can respond to the variation in modelled thermal comfort @urb_geom_mihalakakou_2026. As displayed in @fig:bbox the bounding box spans about 2.5 kilometres north and 2 kilometres east to west. This is to limit the calculation time for SOLWEIG and data download. An area of this size allows for in depth testing without great demands on runtime. 

The bounding box has the following coordinates ((left lower),(right upper)):
- *WSG84 (lat/long)*: ((51°52'46.75",4°27'39.74"), (51°53'48.48",4°28'59.42"))
- *Amersfoort / RD New*: ((91229,432752),(92777,434641))
#figure(
  image("../figs/methods/testing_area.png", width: 100%),
  caption: [
    Red bounding box area for testing
  ],
) <fig:bbox>

=== Data
- *Open Street Map (OSM) @osmnx_geoff_2025: * Base map used for the pedestrian network.
- *ERA5: * European weather model that provides the weather information needed by SOLWEIG.
=== Tools
- *SOLWEIG @lindberg_urban_2017: * Urban microclimate model that estimates thermal comfort on a micro scale.
- *SOLWEIG_GPU @kamath_solweig-gpu_2026: * Implementation of SOLWEIG @lindberg_urban_2017 on GPU that achieves speed-up in terms of computation time.
- *DelftBlue @DHPC2024: * high performance supercomputer TU Delft that was used to do the SOLWEIG_GPU runs.
- *SOLFD @monahan_cool_2025: * Pipeline for generating all the input necessary to run SOLWEIG when given only a bounding box. 
- *UMEP @lindberg_urban_2017: * Urban Multi-scale Environmental Predictor, open-source tool that houses SOLWEIG and other "city-based climate services" @lindberg_urban_2017. 

== Routing tool design
The routing tool has a modular structure, where separate components are all part of the pipeline that make up the pedestrian route planner (see @fig:tool). First, spatial input data were prepared for the selected study area, including the OSM pedestrian network and the input layers required by SOLWEIG. SOLWEIG was then run to produce the hourly UTCI maps. These outputs are linked to the pedestrian network by assigning environmental values from the raster maps to network edges. Finally, the routing component uses these weighted edges to calculate thermally conscious routes, which are made accessible through a web-based interface.

#figure(
  image("../figs/methods/tool_descrip.png", width: 100%),
  caption: [
    Overview of different tool modules.
  ],
) <fig:tool>

The components of the tool were evaluated separately to make the insights generated by the thesis more broadly applicable. Existing research uses a wide variety of methods for thermally informed routing, which suggests that there are multiple valid ways of constructing such a tool. By evaluating each part of the workflow as a component-level design element, the findings can be interpreted independently of the complete implementation. This allows the results to remain relevant for other methodological contexts.

The description in the methodology represents the state after the multiple design iterations. Where applicable the emergent design process is represented by tables showing initial approach, the bottleneck it introduced, and how the approach was revised. More information on the emergent process can be found in @appendix-A. For some elements the initial direction and approach gathered from literature proved sufficient and no revision was necessary to come to the final product.

Finally, the transferability of the tool was assessed by applying the full pipeline to an additional study area in Rotterdam and evaluating its performance in terms of computation time and ease of use. Since a scalable tool should be easily transferable to a different spatial area. #todo[check again...]

==== Requirements
The central design requirement for the tool was scalability. Existing thermally conscious routing methods show that thermally informed routing is possible, but often remain limited to specific study areas. This makes it difficult to apply the same method to larger areas, different cities, or other environmental settings. In this thesis, scalability was therefore considered not only for the final route planner, but for every component in the pipeline.

Firstly, performance was treated both as part of scalability and as a requirement in itself. In a computationally inefficient tool, existing bottlenecks are amplified as the tool scales. At the same time, performance was also important for usability. The routing component needed to generate routes within a reasonable time, especially when users interactively changed origins, destinations, timesteps, or preference settings. Additionally, faster components made iterative development, testing, and debugging more efficient, while also improving the scalability of the complete workflow. However, performance optimization was not treated as an objective in itself. Optimization decisions were weighed against their expected impact on the use case, in order to avoid over-engineering individual components where the practical benefit would be limited.

Secondly, ease of use was considered for all components. A scalable tool should not depend on extensive manual intervention, because manual steps make the workflow slower and more difficult to reproduce. In this context, manual intervention refers to tasks such as searching through separate code fragments, moving files between folders, adjusting file paths, or manually preparing inputs between processing steps. For this reason, the implementation aimed to minimize the manual intervention within the components.

Thirdly, reusability was addressed through a component-based architecture @khalid_software_2025 @mehboob_reusability_2021. The tool was divided into separate modules with low coupling #footnote[Coupling is a term used in software design that describes how dependent software modules are on each other. High coupling means that changes in one module of the software can have big effects on other modules. Low coupling means that the modules are largely independent from each other.] and high cohesion #footnote[Cohesion is closely related to coupling and refers to how well all the elements in a module are supporting a single well-defined purpose. For reusability, low coupling and high cohesion are preferred.]. Each component had a clearly defined purpose and, where necessary, communicated with other components through explicit data formats. This made the components easier to test, replace, or extend without changing the entire pipeline. Reusability also supported scalability, because future applications are unlikely to require the full methodology exactly as developed in this thesis. Depending on the available data, computational resources, and research aim, only specific components may be relevant. The modular design therefore allowed individual parts of the workflow to remain useful even when the complete route planner was not implemented.
#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial approach*][*Bottleneck*][*Revised*],
  [I9],
  [Ease of use, performance, scalability],
  [strong coupling between components introduces performance bottlenecks],
  [modular system design with high cohesion that supports reusability],
), caption: "Emergent process full tool")<tab:full-tool>

=== Data preparation
#todo[say something about ERA5]
#figure(
  image("../figs/methods/ERA5.png", width: 100%),
  caption: [
    Hourly ERA5 climate inputs used for the UMEP/SOLWEIG simulations on 19 July 2022. Values represent the spatial mean of the ERA5 grid cells covering the study area. Radiation variables are shown as hourly mean fluxes, converted from accumulated energy values.
  ],
) <fig:era5>
The simulations were forced with hourly ERA5 meteorological input data for 19 July 2022. The main climate variables used were air temperature, relative humidity, wind conditions, and radiation-related variables, which together define the hourly atmospheric conditions used in the UMEP/SOLWEIG simulations.
// The first component consisted of gathering the pedestrian network from the OSM and the input data for SOLWEIG. Existing research on thermally comfortable routing differs widely in how the input data is collected, and which data is considered in the first place. Largely constrained by data availability. The solution for this problem adopted in this thesis is to use UMC modelling which requires more simplistic input information. This makes the entire workflow more scalable.#todo[unclear section, repetitive?]
#todo[Should remove or not, give introduction that introduces the 'problem' of this step]

==== UMEPIO
#show link: underline
Monahan (2025) @monahan_cool_2025 developed SOLFD, which implements an automated pipeline for collecting the input data required to run SOLWEIG. SOLWEIG requires several spatial input layers, including CHM, DSM, DTM, and land-cover rasters. If these layers have to be collected and processed manually, the workflow becomes time-consuming, difficult to reproduce, and more vulnerable to human error.

However, the pipeline was distributed as separate sections of code in a #link("https://github.com/jsscmnhn/SOLWEIG_SOLFD")[GitHub repository] @solfd_githum, which limited its practical reusability. To address this, the existing SOLFD pipeline was published as a pip package: #link("https://pypi.org/project/umepio/")[UMEPIO]. Packaging the workflow makes it easier to install and reuse, while also standardising the way input data are collected and prepared. This reduces the amount of manual effort required within the data-preparation component and allows the same input-data pipeline to be reused in contexts beyond the route planner developed in this thesis.

==== Pedestrian network
Two main data sources were considered for constructing the pedestrian network. The first option was OpenStreetMap, which is commonly used in routing research because it is open, widely available, and accessible through established tools such as OSMnx. The second option was Overture Maps, which provides cloud-native and normalised network data partly derived from OSM, and was therefore considered potentially preferable from a scalability perspective.

However, manual inspection of the study area showed that some less common tags were not retained in the Overture dataset. This was particularly relevant for pedestrian infrastructure, where sidewalk-related tags were missing. While sidewalk data in OpenStreetMap are not complete or consistently available, the presence of these tags can still improve the spatial representation of the pedestrian environment. This is relevant because pedestrians do not use the centre lines of roads, but generally move along sidewalks or road edges. For this reason, retaining this information was considered more important than using a more normalised network source.

The final workflow therefore used plain OpenStreetMap data, gathered through OSMnx #footnote[OSMnx is a python package that downloads OSM data into a NetworkX representation, allowing for easy access to the data.], as the basis for the transportation network. This choice makes it possible to preserve the sidewalk information. The pedestrian network is not only used for routing, but also for linking SOLWEIG outputs to the walking environment. The location of network edges influenced which raster values were sampled so a close representation of the real world is important. Keeping this information allows for further analysis and prevents unnoticed loss of detail.

A custom filter was applied to gather the pedestrian network from OSM, because the standard OSMnx @osmnx_geoff_2025 pedestrian filter removed information, such as sidewalk tags, that was necessary to retain. Additionally, OSMnx automatically adds two edges per node pair to indicate that both directions are accessible. This doubles the size of the network, which was undesirable in this use case because the edge annotation process loops over every edge (see @mth:annotation). Therefore, the network was saved as an undirected graph, in which each node pair was connected by a single bidirectional edge. This almost halved the storage requirement while preserving the necessary routing structure.
#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I1],
  [Use the SOLFD pipeline directly from its original code distribution],
  [The pipeline was difficult to install and run because of how the code was distributed],
  [Distribute the SOLFD pipeline as a PyPI package],
  [I3],
  [Standard filtered OSMnx],
  [Loss of tags],
  [Personal pedestrian filtering],
  [I3],
  [Multiple ways to tag the same thing],
  [routing requires flattened representation, but we don't want to lose any information],
  [Add personal pedestrian tags],
  [I4],
  [Bi-directionality in standard representation enforced through double edges],
  [Redundant information increases storage demand],
  [Change network representation to undirected],
  [I2],
  [Centre lines],
  [Pedestrians do not use the center lines of the road],
  [Solution out of scope: provide analysis for future work],
),
caption: "Emergent process data preparation"
)
=== SOLWEIG execution
For scalability running SOLWEIG introduced two main challenges:
- *Space:* SOLWEIG produces raster-based outputs for several environmental variables, including UTCI. For each timestep, one for every hour in the day, these outputs represent the entire study area as a raster layer. As a result, the total data volume increases rapidly when additional weather scenarios are included or when the spatial extent is expanded. This creates a scalability problem: storing the full model output for every possible routing context would require large amounts of storage and would make the data slower to access during route calculation.
- *Time:* The computational cost of running UMEP simulations is substantial. Using SOLWEIG\_GPU @kamath_solweig-gpu_2026, processing a 2 km by 2 km area at a 0.5 m resolution required approximately 20–40 minutes, depending on the available hardware.

For these problems, two solutions were investigated. The first was a _generalist_ approach, in which UMEP would be run on demand. This would reduce storage requirements, since the collection of input data and running of the model would be done only when a route is requested. However, this shifts the bottleneck to input-data collection. If the full tile surrounding the route of input data still needs to be collected and stored, there is little advantage over storing the model outputs directly. Alternatively, collecting smaller tiles around the route would require many requests to an external data server, such as PDOK. This would greatly increase latency and create a dependency on an external source during route calculation. For a scalable route planner, this is undesirable because it makes the system slower and less reliable.

The second solution was a _specialist_ approach, in which UMEP outputs are precomputed for the study area and transformed before storage to become a manageable size. The computation time can then be moved to an external machine depending on hardware availability. This approach was chosen for this thesis. SOLWEIG\_GPU was run on the DelftBlue supercomputer which has multiple GPUs shared across the university. The performance (computation time) of SOLWEIG\_GPU was entirely dependent on the RAM available. With tests on the same GPU having either 10GB or 80GB of RAM produces computation times for the test area of 37 minutes or 18 minutes respectively. These large differences indicated that a full performance benchmark would not be additive to this research, since any further work would most likely have access to different hardware anyway. Tile size was not tested but determined using the recommendations provided by the developers of SOLWEIG\_GPU @kamath_solweig-gpu_2026. 

The output of SOLWEIG-GPU consists of multiple partially overlapping raster tiles, which must be merged to reconstruct a continuous raster for the full study area. The overlap between adjacent tiles is specified as an input parameter during the SOLWEIG-GPU simulation. During the merging process, this overlap is divided between neighbouring tiles: each tile is cropped along its internal edges by half of the overlap distance before the remaining raster sections are joined. This prevents duplicate representation of overlapping cells while preserving the full spatial extent of the modelled area.

To assess the computational implications of spatial resolution, the raster data were processed at multiple resolutions and the corresponding runtimes were recorded and compared. #todo[Run the entire thing also for resolution1, need to do that anyway.]

#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I5],
  [Run umep on demand on small area],
  [Gathering input data too slow],
  [methodological approach abandoned],
  [I6],
  [Use external compute infrastructure],
  [Performance depended strongly on available hardware],
  [Do tests on the available hardware before defining the workflow],
),
caption: "Emergent process UMEP execution"
)
=== Network annotation
<mth:annotation>
This component links the SOLWEIG outputs to the pedestrian network by transforming raster-based UTCI data into edge-level network attributes. The SOLWEIG output represents thermal conditions as continuous raster surfaces for each timestep, whereas the routing algorithm operates on a graph in which costs are assigned to individual edges. Therefore, the raster values cannot be used directly during route calculation. They first need to be aggregated into a single representative value, for each network edge. This transformation converts the spatially detailed UTCI output into a graph-based representation that is compatible with the routing algorithm.

To achieve this, the SOLWEIG raster outputs were sampled along the geometries of the pedestrian network and transformed into edge-level attributes. For each edge, the raster cells intersected by its geometry were identified, after which the UTCI values from each of the 24 raster bands were sampled. The values of all intersecting cells within a single band were then aggregated by taking the median, resulting in one representative `utci_median` value per timestep. These median values were mapped to their corresponding UTCI thermal-stress categories and stored on the edge as the attribute `utci_category` @utci-categories. This compact edge-level representation allows the spatially detailed raster output to be incorporated directly into the edge weights used by the routing algorithm.

The algorithm does for every edge in the graph $G(V, E)$:
1. Get the geometry of the edge.
2. Identify the raster cell indices of all cells intersected by the edge geometry.
3. Extract the UTCI values from all 24 raster bands for the intersecting cells.
4. For each raster band, aggregate the sampled cell values into a single representative edge value.
5. Store the resulting 24 values as an edge attribute.

#figure(
  table(
    columns: 2,
    table.header[*UTCI (deg C)*][*Thermal stress*],
    [> 46],
    [Extreme heat stress],
    [38 to 46],
    [Very strong heat stress],
    [32 to 38],
    [Strong heat stress],
    [26 to 32],
    [Moderate heat stress],
    [9 to 26],
    [No thermal stress],
    [0 to 9],
    [Slight cold stress],
    [-13 to 0],
    [Moderate cold stress],
    [-27 to -13],
    [Strong cold stress],
    [< -40 ],
    [Extreme cold stress]
  ), 
  caption: [UTCI categories as defined for SOLWEIG @utci_Blazejczyk_2013 .]
)<utci-categories>

Where the categories in @utci-categories represent increasingly high penalties to the edge weight. This is in line with findings from Basu et al. (2024), who found that higher UTCI categories have "non-uniform and possibly exponential" effect on perceived walking distance @basu_hot_2024. Using categories of an outdoor thermal comfort index to assign edge weights is consistent with the methodological approach of Ma et al. (2025), who applied PET-based categories for this purpose @ma_active_2025. In this thesis, UTCI was used instead of PET due to the absence of detailed wind information. Nevertheless, the underlying principle remains comparable, as both approaches translate thermal comfort categories into routing penalties.

To do the sampling efficiently the the SOLWEIG output was transformed to a file format suited to spatial access. The merged SOLWEIG output was saved to a .Zarr file, which is a cloud optimized file format that allows efficient access to multidimensional raster data (See @imp:zarr) Compared with the previous .tif-based workflow, this reduced the annotation time from approximately five minutes to ten seconds. 

The annotated network is saved as two GeoParquet files, one containing the edges and one containing the nodes, using a shared custom data schema. This schema acts as the translation layer between the network representation used by the annotator and the router, as shown in @fig:network-schema. In addition to improving consistency between both components, this representation also reduced storage requirements. The original OSMnx GraphML file required approximately 26 MB, whereas the equivalent GeoParquet representation required only about 1 MB.

#figure(
  image("../figs/methods/network_schema.png", width: 80%),
  caption: [
    Shared network representation
  ],
) <fig:network-schema>
#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I7],
  [Sample edge geometry from merged tif],
  [Multiple lookups for every band negatively impact performance],
  [Merge tif tiles in a .Zarr format],
  [I8],
  [Use OSMnx networkX representation],
  [Introduces performance issues during routing],
  [Shared data schema and storage in geoparquet, storing nodes, edges and metadata],
  ),
  caption: "Emergent process network annotation"
)<table-annotation>

=== Routing Prototype

This component uses the annotated pedestrian network both for visualization in the front-end and for applying the routing algorithm in the back-end. The front-end and back-end communicate through an API, which supports the broader requirement of reusability. Separating these components prevents the routing logic from becoming dependent on the interface. This is especially relevant at larger spatial scales, where executing routing operations directly in the front-end could introduce performance constraints.

The network is loaded from the shared `NetworkSchema` and converted into a node-edge representation using NumPy, while maintaining an adjacency list for efficient graph traversal. This representation was selected because it is conceptually transparent and computationally efficient for the pedestrian routing tasks.

A substantial body of literature exists on “pleasant” or heat-aware routing. So the requirements for the routing algorithm gathered from literature were quite good. In line with previous work the algorithm is an implementation of weighted Dijkstra @rusig_reducing_2017 @wen_walking_smart_2025 @aliyev1_exploiting_2025 @aliyev2_vehicle-pedestrian_2025 @ma_active_2025. With the algorithm having the following two characteristics:
1. The algorithm should be dynamic, meaning that edge weights are not fixed in advance but depend on the pedestrian’s state as they reach each node. This state is shaped by the intensity and duration of prior heat exposure during walking and can therefore influence the weighting of subsequent edges, as demonstrated by Wen et al. (2025), Rußig and Bruns (2017), and Zhao et al. (2024) @wen_walking_smart_2025 @rusig_reducing_2017 @zhao_impact_2024.
2. The routing process should not rely solely on researcher-defined weights, as this would impose fixed assumptions about the relative importance of environmental factors. Instead, it should incorporate user-defined environmental preferences, similar to the approach proposed by Novack et al. (2018) @novack_system_2018. 

The first requirement reflects that experienced thermal discomfort is cumulative and dynamic. Heat stress is not determined only by conditions on individual street segments, but also by the intensity and duration of exposure accumulated along the route. The routing algorithm therefore carries a route state through the search, representing the pedestrian’s accumulated heat exposure at each node. As a result, the same physical node can be reached under different thermal conditions. 

The algorithm therefore stores costs for combinations of node and route state, rather than only one least cost per node as in a standard shortest-path implementation. This allows accumulated heat exposure to influence subsequent edge costs, which is implemented through the dynamic sensitivity function. When pedestrians traverse multiple thermally stressful edges consecutively, this function increases the penalty assigned to further heat exposure. This is in line with Zhao et al. (2024), who found that the thermal sensation is also shaped by the heat experienced before it @zhao_impact_2024. Consequently, the algorithm increases the relative importance of cooler or shaded alternatives after sustained heat exposure.

The second requirement is motivated by the usability of the tool. Instead of only imposing fixed researcher-defined trade-offs between route length and thermal comfort, users are able to indicate their own preferences. This allows the routing behaviour to adapt to different pedestrian needs.

==== Edge cost calculation
Each edge in the pedestrian network receives a generalized cost:
#set align(center)
  $C_e​=L_e​⋅(1+P_e​)$

#set align(left)
where $C_e$ is the edge cost, $L_e$ is the edge length in meters and $P_e$ is the normalized environmental penalty multiplier. This formulation ensures that route length always remains part of the optimization problem. For example, extremely hot but short edges may still be preferable to substantially longer detours, while longer exposure on moderately hot routes should still be captured.

The environmental penalty is defined as:
#set align(center)
  $P_e = sum_(i=1)^n w_i  * p_i * gamma_i (s)$
#set align(left)
where $w_i$ represents the user-defined importance of environmental variable $i$, 
$p_i$ is the normalized environmental penalty associated with edge $e$ and variable $i$,
and $gamma_i(s)$ is a dynamic sensitivity function dependent on the route-state $s$. 

The environmental penalty scales with the severity of the heat stress @basu_hot_2024. These multipliers effectively increase the distance of hot edges, which makes the algorithm more likely to choose a slightly longer route that is more comfortable. 

#figure(
  table(
  columns: (2fr, 1fr),
  inset: 8pt,
  stroke: 0.5pt,
  align: (left, center),

  [*Heat stress*], [*Multiplier*],
  [No thermal stress], [0.00],
  [Moderate heat], [0.10],
  [Strong heat], [0.35],
  [Very strong heat], [1.00],
  [Extreme heat / near-avoid], [3.00],
  ), 
  caption: [Heat stress categories and their associated penalty multipliers used in the routing algorithm.]
)<tab:heat_multipliers>

The application was developed in a fully Python-based environment as a tool for communicating and testing the routing logic. Since numerous front-end frameworks and implementation strategies could have been used, detailed exploration of front-end development was considered outside the scope of the research. Due to its limited relevance to the research question. The front-end was therefore deployed as a prototype, while remaining separated from the routing logic. This ensures that the routing component and the broader processing pipeline remain reusable for other applications.

The interface uses a #link("https://maplibre.org/projects/gl-js/")[MapLibreGL map], on which the pedestrian network can be displayed for each hourly timestep. A separate page allows the user to select two points on the map, choose a timestep, and adjust their preference settings. The generated route is then displayed on the map.

#figure(
table(
  columns: 4,
  table.header[*Insight*][*Initial*][*Bottleneck*][*Revised*],
  [I8],
  [NetworkX representation],
  [Performance issues at scale],
  [Custom network representation],
  [I9],
  [Application also does routing],
  [Coupling of elements can negatively effect reusability and client-side calculation of routes introduces performance constraints],
  [Separate routing from the application and communicate between the two via an API]
),
  caption: "Emergent process routing network"
)<table-routing>

== Validation and evaluation of the route planner 
<validation>
In this thesis there is a distinction between validation and evaluation. Validation refers to testing the route planner’s output in a structured way, by examining how much UTCI exposure decreases compared with the shortest route, how much additional distance this requires, and how spatially different the resulting thermal-comfort routes are from the original shortest-distance routes. While evaluation encompasses the reflexive method used to generate the generalizable insights from the design iterations. The evaluation method was described in @research-approach and an overview with the insights can be found in @appendix-A. 

The validation was performed as follows:
1. *Manual validation: * Two routes with a large difference between the shortest and most comfortable path were manually evaluated. This evaluation is done using the original SOLWEIG output maps to validate that the flattening is not causing any meaningful data loss or changes. This method is less structured, but aligns with how validation was happening naturally during the development process. 

2. *Structured validation: * This method was used for final validation, but also for tuning the variable weights and attribute choices in the algorithm. For this purpose, a stratified origin-destination (OD) test set was created. The test set consists of randomly sampled OD pairs from the pedestrian network, grouped into distance-based categories. The distance between an origin and destination is calculated as a straight-line distance: geodesic distance is used when the coordinates appear to be longitude-latitude coordinates, while Euclidean distance is used otherwise. The maximum possible OD distance is estimated from the bounding box of the node dataset.  

- `short`: 100 to 400 meters.
- `short_mid`: 400 to 750 meters.
- `medium`: 750 to 1100 meters.
- `medium_long`: 1100 to 1500 meters
- `max_distance`: above 1500 and between the estimated max available distance based on the bounding box.

For every category 100 OD pairs were generated where the directions were also randomized. Plot of OD pairs in @fig:OD_pairs.

#figure(
  image("../figs/methods/OD_pairs.png", width: 100%),
  caption: [The five categories of OD pairs.]
) <fig:OD_pairs>

This validation serves more as a sensibility test than a true validation of thermal comfort along the routes. The validation aims to show that the thermally comfortable routes are notably different from the shortest path; in distance and average temperature. But also that the algorithm behaves in a predictable way for different types of routes. 